multimedia/mscore: Updated for version 1.2.
Signed-off-by: dsomero <xgizzmo@slackbuilds.org>

diff --git a/multimedia/mscore/mscore.SlackBuild b/multimedia/mscore/mscore.SlackBuild
--- a/multimedia/mscore/mscore.SlackBuild
+++ b/multimedia/mscore/mscore.SlackBuild
@@ -1,19 +1,16 @@
 #!/bin/sh
 # Slackware build script for mscore
-# Written by Larry Hajali <larryhaja[at]gmail[dot]com>
+# Maintained by Klaatu at memeber.fsf dot org
 
-SRCNAM=MuseScore
 PRGNAM=mscore
-VERSION=${VERSION:-0.9.5}
+VERSION=${VERSION:-1.2}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 
-# Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
     i?86) ARCH=i486 ;;
     arm*) ARCH=arm ;;
-    # Unless $ARCH is already set, use uname -m for all other archs:
        *) ARCH=$( uname -m ) ;;
   esac
 fi
@@ -22,6 +19,21 @@ CWD=$(pwd)
 TMP=${TMP:-/tmp/SBo}
 PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
+
+set -e
+
+rm -rf $PKG
+mkdir -p $TMP $PKG $OUTPUT
+cd $TMP
+rm -rf $PRGNAM-$VERSION
+tar xvf $CWD/$PRGNAM-$VERSION.tar.bz2
+cd $PRGNAM-$VERSION
+chown -R root:root .
+find . \
+ \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
+ -exec chmod 755 {} \; -o \
+ \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
+ -exec chmod 644 {} \;
 
 if [ "$ARCH" = "i486" ]; then
   SLKCFLAGS="-O2 -march=i486 -mtune=i686"
@@ -32,61 +44,36 @@ elif [ "$ARCH" = "i686" ]; then
 elif [ "$ARCH" = "x86_64" ]; then
   SLKCFLAGS="-O2 -fPIC"
   LIBDIRSUFFIX="64"
+  #must hardcode arch or it fails as 32bit
+  sed -i 's|m32|m64|' ./$PRGNAM/CMakeLists.txt
 else
   SLKCFLAGS="-O2"
   LIBDIRSUFFIX=""
 fi
 
-set -e
-
-rm -rf $PKG
-mkdir -p $TMP $PKG $OUTPUT
-cd $TMP
-rm -rf $PRGNAM-$VERSION
-tar xvf $CWD/$SRCNAM-$VERSION.tar.bz2
-cd $PRGNAM-$VERSION/$PRGNAM
-chown -R root:root .
-find . \
- \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
- -exec chmod 755 {} \; -o \
- \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
- -exec chmod 644 {} \;
-
-# Remove unneeded *.ts locale files
-sed -i '/\.ts/d' share/locale/CMakeLists.txt
-
-# fix .desktop file.
+# touchup the .desktop file
 sed -i \
   -e '/^Categories/s|=.*|=Application;Qt;AudioVideo;|' \
-  -e 's|true|false|' packaging/mscore.desktop
+  -e 's|true|false|' ./$PRGNAM/packaging/mscore.desktop
 
-# This would build QtScript bindings, which are already present in
-# 13.0's qtscriptgenerator package
-sed -i 's|scriptgen ||' CMakeLists.txt
+  make release PREFIX=/usr
+  make install PREFIX=/usr DESTDIR=$PKG
 
-mkdir build && cd build
-  lrelease ../share/locale/*.ts
-  cmake \
-    -DCMAKE_CXX_FLAGS_RELEASE="$SLKCFLAGS -DQT_NO_DEBUG" \
-    -DCMAKE_INSTALL_PREFIX=/usr \
-    -DLIB_SUFFIX=$LIBDIRSUFFIX \
-    -DQT45=TRUE \
-    -DCMAKE_BUILD_TYPE=Release \
-    ..
+# include the icon file
+install -D -m 0644 ./$PRGNAM/packaging/mscore.desktop \
+  $PKG/usr/share/applications/mscore.desktop
+install -D -m 0644 ./$PRGNAM/mscore/data/mscore.xpm \
+  $PKG/usr/share/pixmaps/mscore.xpm
 
-  make
-  make install DESTDIR=$PKG
-cd -
+mkdir -p $PKG/usr/man/man1
+gzip -9c ./$PRGNAM/packaging/$PRGNAM.1 > $PKG/usr/man/man1/$PRGNAM.1.gz
 
 find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
   | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
 
-mkdir -p $PKG/usr/man/man1
-gzip -9c packaging/$PRGNAM.1 > $PKG/usr/man/man1/$PRGNAM.1.gz
-
 mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
 cp -a \
-  ChangeLog COPYING NEWS README* \
+  ./$PRGNAM/{ChangeLog,COPYING,NEWS,README,README.scripts} \
   $PKG/usr/doc/$PRGNAM-$VERSION
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
