desktop/wmtime: New maintainer, add multiple language support.

diff --git a/desktop/wmtime/wmtime.SlackBuild b/desktop/wmtime/wmtime.SlackBuild
--- a/desktop/wmtime/wmtime.SlackBuild
+++ b/desktop/wmtime/wmtime.SlackBuild
@@ -2,16 +2,26 @@
 
 # Slackware build script for wmtime
 
-# Written by Pablo Santamaria (pablosantamaria@gmail.com)
+# Originally written by Pablo Santamaria (email removed)
+
+# Now maintained by B. Watson <yalhcru@gmail.com>. Original version
+# had no license, modified version released under the WTFPL. See
+# http://www.wtfpl.net/txt/copying/ for details.
+
+# 20170210 bkw:
+# - Take over maintenance, BUILD=2
+# - i486 => i586
+# - Make the language stuff work, support LANGUAGE variable
+# - Add Spanish, French, German language support.
 
 PRGNAM=wmtime
 VERSION=${VERSION:-1.0b2}
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 TAG=${TAG:-_SBo}
 
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
-    i?86) ARCH=i486 ;;
+    i?86) ARCH=i586 ;;
     arm*) ARCH=arm ;;
        *) ARCH=$( uname -m ) ;;
   esac
@@ -22,8 +32,8 @@ TMP=${TMP:-/tmp/SBo}
 PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
 
-if [ "$ARCH" = "i486" ]; then
-  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
+if [ "$ARCH" = "i586" ]; then
+  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "i686" ]; then
   SLKCFLAGS="-O2 -march=i686 -mtune=i686"
@@ -51,18 +61,31 @@ find -L . \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
  -exec chmod 644 {} \;
 
-cd $PRGNAM
-sed -i "s/cc -c/cc -c -fgnu89-inline $SLKCFLAGS/" Makefile
-make
-mkdir -p $PKG/usr/bin
-  cp -a wmtime $PKG/usr/bin
-  strip --strip-unneeded $PKG/usr/bin/wmtime
-cd ..
+# make the language stuff actually work
+sed -i \
+  "s,fopen(\"language\",fopen(\"/usr/share/$PRGNAM/language\"," \
+  $PRGNAM/$PRGNAM.c
+
+# much as I like the Beatles, we can't have 8 weekday names here:
+sed -i '8d' languages/slovene.lang
+
+sed -i "s/cc -c/cc -c -fgnu89-inline $SLKCFLAGS/" $PRGNAM/Makefile
+make -C $PRGNAM
+mkdir -p $PKG/usr/bin $PKG/usr/share/$PRGNAM/languages
+install -m0755 -s $PRGNAM/$PRGNAM $PKG/usr/bin
+install -m0644 languages/* $CWD/*.lang $PKG/usr/share/$PRGNAM/languages
+
+LANGUAGE="${LANGUAGE:-us}"
+if [ -e $PKG/usr/share/$PRGNAM/languages/$LANGUAGE.lang ]; then
+  ln -s languages/$LANGUAGE.lang $PKG/usr/share/$PRGNAM/language
+else
+  echo "Invalid LANGUAGE '$LANGUAGE'. Supported values are:" 2>&1
+  ls $PKG/usr/share/$PRGNAM/languages/*.lang | sed 's,.*/\([^/]*\)\.lang,\1,g'
+  exit 1
+fi
 
 mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a \
-  BUGS CHANGES COPYING HINTS INSTALL README TODO \
-  $PKG/usr/doc/$PRGNAM-$VERSION
+cp -a BUGS CHANGES COPYING HINTS README TODO $PKG/usr/doc/$PRGNAM-$VERSION
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
 mkdir -p $PKG/install
