office/zathura-pdf-mupdf: Use mupdf-legacy dep.
Signed-off-by: B. Watson <yalhcru@gmail.com>

diff --git a/office/zathura-pdf-mupdf/zathura-pdf-mupdf.SlackBuild b/office/zathura-pdf-mupdf/zathura-pdf-mupdf.SlackBuild
--- a/office/zathura-pdf-mupdf/zathura-pdf-mupdf.SlackBuild
+++ b/office/zathura-pdf-mupdf/zathura-pdf-mupdf.SlackBuild
@@ -8,7 +8,7 @@
 
 PRGNAM=zathura-pdf-mupdf
 VERSION=${VERSION:-0.3.2}
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 TAG=${TAG:-_SBo}
 
 if [ -z "$ARCH" ]; then
@@ -40,6 +40,15 @@ fi
 
 set -e
 
+if [ ! -d /opt/mupdf-legacy ]; then
+  echo "*** Missing required dependency 'mupdf-legacy'" 1>&2
+  exit 1
+fi
+
+# Use old libs/headers. Works even if a newer mupdf is installed in /usr.
+PKG_CONFIG_PATH=/opt/mupdf-legacy/lib$LIBDIRSUFFIX/pkgconfig:$PKG_CONFIG_PATH
+export PKG_CONFIG_PATH
+
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
@@ -47,11 +56,8 @@ rm -rf $PRGNAM-$VERSION
 tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
 cd $PRGNAM-$VERSION
 chown -R root:root .
-find -L . \
- \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 -o -perm 511 \) \
- -exec chmod 755 {} \; -o \
- \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
- -exec chmod 644 {} \;
+find -L .  -perm /111 -a \! -perm 755 -a -exec chmod 755 {} \+ -o \
+        \! -perm /111 -a \! -perm 644 -a -exec chmod 644 {} \+
 
 # Upstream left the README out of the release tarball for some reason.
 cat $CWD/upstream.README > README
@@ -61,11 +67,12 @@ cat $CWD/upstream.README > README
 sed -i \
   -e "s,-fPIC,$SLKCFLAGS," \
   -e '/^MUPDF_LIB/s,-.*,$(shell pkg-config --libs mupdf),' \
+  -e '/^INCS/s,= ,&$(shell pkg-config --cflags mupdf) ,' \
   config.mk
 
 PLUGDIR=/usr/lib$LIBDIRSUFFIX/zathura
 
-make
+make VERBOSE=1
 strip *.so
 make install DESTDIR=$PKG PLUGINDIR="$PLUGDIR/pdf-mupdf"
 
