audio/ladspa_sdk: Moved from multimedia

diff --git a/audio/ladspa_sdk/ladspa_sdk.SlackBuild b/audio/ladspa_sdk/ladspa_sdk.SlackBuild
--- a/audio/ladspa_sdk/ladspa_sdk.SlackBuild
+++ b/audio/ladspa_sdk/ladspa_sdk.SlackBuild
@@ -1,9 +1,8 @@
 #!/bin/sh
 
 # Slackware build script for ladspa-sdk
-# Written by ppr:kut <hmwiesinger@gmx.at>
 
-# Copyright 2007  Heinz Wiesinger
+# Copyright 2007-2008 Heinz Wiesinger <hmwiesinger@gmx.at>
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -29,8 +28,9 @@
 PRGNAM=ladspa_sdk
 VERSION=1.13
 ARCH=${ARCH:-i486}
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 TAG=${TAG:-_SBo}
+
 CWD=$(pwd)
 TMP=${TMP:-/tmp/SBo}
 PKG=$TMP/package-$PRGNAM
@@ -40,6 +40,8 @@ if [ "$ARCH" = "i486" ]; then
   SLKCFLAGS="-O2 -march=i486 -mtune=i686"
 elif [ "$ARCH" = "i686" ]; then
   SLKCFLAGS="-O2 -march=i686 -mtune=i686"
+elif [ "$ARCH" = "x86_64" ]; then
+  SLKCFLAGS="-O2 -fPIC"
 fi
 
 set -e
@@ -65,10 +67,15 @@ cd src
     INSTALL_INCLUDE_DIR="$PKG/usr/include"
 cd -
 
-( cd $PKG
-  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
-  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
-)
+mkdir -p $PKG/etc/profile.d/
+cp $CWD/profile.d/* $PKG/etc/profile.d/
+chmod 0755 $PKG/etc/profile.d/*
+
+# Cleanup files left in /tmp by make
+rm -f /tmp/test.wav || true
+
+find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
+  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
 
 mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
 cp -a README doc/* $PKG/usr/doc/$PRGNAM-$VERSION
