games/adom: Updated for version 1.2.0_pre5 (supports also x86_64).
Signed-off-by: Matteo Bernardini <ponce@slackbuilds.org>

diff --git a/games/adom/adom.SlackBuild b/games/adom/adom.SlackBuild
--- a/games/adom/adom.SlackBuild
+++ b/games/adom/adom.SlackBuild
@@ -1,21 +1,39 @@
 #!/bin/sh
 
-# Slackware packager script for ADOM
+# Slackware package script for ADOM
 # Written by pyllyukko - pyllyukko AT maimed dot org
 #
 # ADOM ships as a binary, so this script just wraps it up
 # in a clean .tgz package, ready to be installed.
 
 PRGNAM=adom
-VERSION=${VERSION:-1.1.1}
+VERSION=${VERSION:-1.2.0_pre5}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
-ARCH=i386
+
+if [ -z "$ARCH" ]; then
+  case "$( uname -m )" in
+    i?86) ARCH=i486 ;;
+    arm*) ARCH=arm ;;
+       *) ARCH=$( uname -m ) ;;
+  esac
+fi
 
 CWD=$(pwd)
 TMP=${TMP:-/tmp/SBo}
 PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
+
+if [ "$ARCH" = "i486" ]; then
+  ARCHBITS=32
+elif [ "$ARCH" = "i686" ]; then
+  ARCHBITS=32
+elif [ "$ARCH" = "x86_64" ]; then
+  ARCHBITS=64
+else
+  echo "error: unsupported architecture!" 1>&2
+  exit 1
+fi
 
 set -e
 
@@ -23,7 +41,7 @@ rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
 rm -rf $PRGNAM
-tar xvf $CWD/$PRGNAM-${VERSION//./}-elf.tar.gz
+tar xvf $CWD/${PRGNAM}_linux_debian_${ARCHBITS}_${VERSION}.tar.gz
 cd $PRGNAM
 chown -R root:root .
 find . \
@@ -32,13 +50,12 @@ find . \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
  -exec chmod 644 {} \;
 
-mkdir -pv ${PKG}/usr/games
-cp -v adom ${PKG}/usr/games
+install -m 0755 -D $PRGNAM $PKG/usr/games/$PRGNAM
 
 mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a \
-  adomfaq.txt manual.doc readme.1st \
-  $PKG/usr/doc/$PRGNAM-$VERSION
+#cp -a \
+#  adomfaq.txt manual.doc readme.1st \
+#  $PKG/usr/doc/$PRGNAM-$VERSION
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
 # Copy the slack-desc into ./install
