audio/mhwaveedit: Updated for version 1.4.24, new maintainer.
Signed-off-by: B. Watson <yalhcru@gmail.com>

diff --git a/audio/mhwaveedit/mhwaveedit.SlackBuild b/audio/mhwaveedit/mhwaveedit.SlackBuild
--- a/audio/mhwaveedit/mhwaveedit.SlackBuild
+++ b/audio/mhwaveedit/mhwaveedit.SlackBuild
@@ -2,16 +2,27 @@
 
 # Slackware build script for mhwaveedit
 # Written by Felix Krueger
-# contact: flex[dot]krueger[at]googlemail[dot]com
+
+# Now maintained by B. Watson <yalhcru@gmail.com>. Original script
+# had no license. Modified version licensed under the WTFPL. See
+# http://www.wtfpl.net/txt/copying/ for details.
+
+# 20181022 bkw:
+# - Take over maintenance.
+# - Update for v1.4.24. Incompatible changes, can't build old version.
+# - Add PULSE and OSS env vars.
+# - If JACK support is built-in, do the realtime stuff.
+# - Minor script cleanups.
+# - Don't install the install directions in docdir.
 
 PRGNAM=mhwaveedit
-VERSION=${VERSION:-1.4.23}
+VERSION=${VERSION:-1.4.24}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
-    i?86) ARCH=i486 ;;
+    i?86) ARCH=i586 ;;
     arm*) ARCH=arm ;;
        *) ARCH=$( uname -m ) ;;
   esac
@@ -23,7 +34,7 @@ PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
 
 if [ "$ARCH" = "i486" ]; then
-  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
+  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "i686" ]; then
   SLKCFLAGS="-O2 -march=i686 -mtune=i686"
@@ -36,26 +47,31 @@ else
   LIBDIRSUFFIX=""
 fi
 
-set -eu
+set -e
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
 rm -rf $PRGNAM-$VERSION
-tar xvf $CWD/$PRGNAM-$VERSION.tar.bz2
+tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
 cd $PRGNAM-$VERSION
 chown -R root:root .
-find -L . \
- \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
-  -o -perm 511 \) -exec chmod 755 {} \; -o \
- \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
-  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
+find -L .  -perm /111 -a \! -perm 755 -a -exec chmod 755 {} \+ -o \
+        \! -perm /111 -a \! -perm 644 -a -exec chmod 644 {} \+
 
-# Fix "unknown type name 'Intbox'"
-patch -p0 < $CWD/intbox.diff
+# 20181023 bkw: environment variables to control the build options.
+MIXER="${MIXER:-xterm -e alsamixer}"
+PULSE="${PULSE:-yes}"
+OSS="${OSS:-no}"
+
+[ "$PULSE" = "no" ] && EXTRAOPTS="$EXTRAOPTS --without-pulse"
+[ "$OSS" =   "no" ] && EXTRAOPTS="$EXTRAOPTS --without-oss"
 
 CFLAGS="$SLKCFLAGS" \
   ./configure \
+  --with-default-mixerapp="$MIXER" \
+  $EXTRAOPTS \
+  --with-default-ladspa-path=/usr/lib$LIBDIRSUFFIX/ladspa \
   --prefix=/usr \
   --libdir=/usr/lib${LIBDIRSUFFIX} \
   --sysconfdir=/etc \
@@ -69,27 +85,29 @@ CFLAGS="$SLKCFLAGS" \
 
 make
 make install DESTDIR=$PKG
+strip $PKG/usr/bin/$PRGNAM
+gzip $PKG/usr/man/man1/$PRGNAM.1
 
-find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
-  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
-
-find $PKG/usr/man -type f -exec gzip -9 {} \;
-for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
-
-mkdir -p $PKG/usr/share/applications
+mkdir -p $PKG/usr/share/applications $PKG/usr/share/pixmaps
 cat $CWD/$PRGNAM.desktop > $PKG/usr/share/applications/$PRGNAM.desktop
-
-mkdir -p $PKG/usr/share/icons/hicolor/48x48/apps
-cat $CWD/$PRGNAM.png > $PKG/usr/share/icons/hicolor/48x48/apps/$PRGNAM.png
+ln -s ../icons/hicolor/64x64/apps/$PRGNAM.png $PKG/usr/share/pixmaps/$PRGNAM.png
 
 mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a AUTHORS COPYING ChangeLog INSTALL NEWS README TODO \
-  $PKG/usr/doc/$PRGNAM-$VERSION
+cp -a AUTHORS COPYING ChangeLog NEWS README TODO $PKG/usr/doc/$PRGNAM-$VERSION
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
 cat $CWD/doinst.sh > $PKG/install/doinst.sh
+
+# realtime audio stuff only if JACK support included.
+if ldd $PKG/usr/bin/$PRGNAM | grep -q libjack; then
+  if [ "${SETCAP:-yes}" = "yes" ]; then
+    cat $CWD/setcap.sh >> $PKG/install/doinst.sh
+    chown root:audio $PKG/usr/bin/$PRGNAM
+    chmod 0750 $PKG/usr/bin/$PRGNAM
+  fi
+fi
 
 cd $PKG
 /sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
