system/open-vm-tools: Update script.
Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/system/open-vm-tools/open-vm-tools.SlackBuild b/system/open-vm-tools/open-vm-tools.SlackBuild
--- a/system/open-vm-tools/open-vm-tools.SlackBuild
+++ b/system/open-vm-tools/open-vm-tools.SlackBuild
@@ -3,6 +3,7 @@
 # Slackware build script for open-vm-tools
 
 # Copyright 2017 Jeremy HOCDE
+# Copyright 2018 Alexander VERBOVETSKY
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -23,8 +24,8 @@
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 PRGNAM=open-vm-tools
-VERSION=${VERSION:-10.2.0_7253323}
-BUILD=${BUILD:-1}
+VERSION=${VERSION:-10.2.0_7253323} # Remember to change VERSION - to _ !!!
+BUILD=${BUILD:-2}
 TAG=${TAG:-_SBo}
 
 SRCVER=$(echo $VERSION | tr _ -)
@@ -56,6 +57,23 @@ else
   LIBDIRSUFFIX=""
 fi
 
+VGAUTH=${VGAUTH:-no}
+case "$VGAUTH" in
+  no)
+    VGAUTH_OPTS="--disable-vgauth"
+    ;;
+  yes)
+    VGAUTH_OPTS=""
+    ;;
+  xmlsec)
+    VGAUTH_OPTS="--enable-xmlsec1"
+    ;;
+  *)
+    echo "eRRoR with VGAUTH parameter"
+    exit 1
+    ;;
+esac
+
 set -e
 
 rm -rf $PKG
@@ -83,8 +101,8 @@ LIBS=-lcrypt \
   --mandir=/usr/man \
   --docdir=/usr/doc/$PRGNAM-$VERSION \
   --without-pam \
-  --without-xerces \
   --without-x \
+  $VGAUTH_OPTS \
   --build=$ARCH-slackware-linux
 
 make
