system/ttf-crosscorefonts: Updated to version 20260427
Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/system/ttf-crosscorefonts/ttf-crosscorefonts.SlackBuild b/system/ttf-crosscorefonts/ttf-crosscorefonts.SlackBuild
--- a/system/ttf-crosscorefonts/ttf-crosscorefonts.SlackBuild
+++ b/system/ttf-crosscorefonts/ttf-crosscorefonts.SlackBuild
@@ -2,6 +2,7 @@
 #
 # Slackware build script for ttf-crosscorefonts.
 #
+# Copyright 2026 Vijay Marcel,India
 # Copyright 2016-2018  Edinaldo P. Silva, Rio de Janeiro, Brazil.
 # All rights reserved.
 #
@@ -10,6 +11,10 @@
 #
 # 1. Redistributions of this script must retain the above copyright
 #    notice, this list of conditions and the following disclaimer.
+#
+# 2. Redistributions in binary form must reproduce the above copyright
+#    notice, this list of conditions and the following disclaimer in
+#    the documentation and/or other materials provided with the distribution.
 #
 #  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
 #  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
@@ -22,19 +27,16 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+
 cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=ttf-crosscorefonts
-VERSION=${VERSION:-20180624}
+VERSION=${VERSION:-20260427}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
-
 ARCH=noarch
 
-# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
-# the name of the created package would be, and then exit. This information
-# could be useful to other scripts.
 if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
   echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
   exit 0
@@ -44,39 +46,59 @@ TMP=${TMP:-/tmp/SBo}
 PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
 
-SRCNAM=${SRCNAM:-noto-fonts}
-SRCVER=${SRCVER:-449470a4d83f6eecdb4a537ab66fcbb5ff28917a}
+FNTA=${FNTA:-tinos}
+FNTB=${FNTB:-Arimo}
+FNTC=${FNTC:-cousine}
+TINOSCOM=${TINOSCOM:-3b4482a99b80ea5fc75f187b1be3120a3f5905b3}
+ARIMOCOM=${ARIMOCOM:-4a6255f269916ae7ad3fc2706b0935e7621396b8}
+COUSINEVER=${COUSINEVER:-v1.241}
 
 set -e
+trap 'echo "$0 FAILED at line $LINENO!" | tee $OUTPUT/error-${PRGNAM}.log' ERR
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
 rm -rf $PRGNAM-$VERSION
-tar xvf $CWD/$SRCNAM-$SRCVER.tar.gz --exclude=alpha --exclude=hinted/{Noto*.ttf,Noto*.ttc} \
---exclude=images --exclude=unhinted
-mv $SRCNAM-$SRCVER $PRGNAM-$VERSION
-cd $PRGNAM-$VERSION
+mkdir -pv $PRGNAM
+tar xvf $CWD/$FNTA-$TINOSCOM.tar.gz -C $PRGNAM
+tar xvf $CWD/$FNTB-$ARIMOCOM.tar.gz -C $PRGNAM
+unzip $CWD/$FNTC-$COUSINEVER.zip -d $PRGNAM
+cd $PRGNAM
 chown -R root:root .
 find -L . \
  \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
-  -o -perm 511 \) -exec chmod 755 {} \; -o \
+  -o -perm 511 \) -exec chmod 755 {} \+ -o \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
-  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
+  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \+
 
-find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
-  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
+install -dv $PKG/usr/share/fonts/TTF/
+install -dv $PKG/usr/share/fonts/OTF/
+mkdir -pv $PKG/usr/doc/$PRGNAM-$VERSION/{tinos,arimo,cousine}
 
-install -d $PKG/usr/share/fonts/TTF/
-install -m644 hinted/*.ttf $PKG/usr/share/fonts/TTF/
+cd $FNTA-$TINOSCOM
+install -m644 fonts/ttf/*.ttf $PKG/usr/share/fonts/TTF/
+install -m644 fonts/otf/*.otf $PKG/usr/share/fonts/OTF/
+cp -av OFL.txt $PKG/usr/doc/$PRGNAM-$VERSION/tinos
 
-mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp FAQ.md issue_template.md LICENSE NEWS.md README.md $PKG/usr/doc/$PRGNAM-$VERSION/
+cd .. && cd $FNTB-$ARIMOCOM
+install -m644 fonts/ttf/*.ttf $PKG/usr/share/fonts/TTF/
+install -m644 fonts/otf/*.otf $PKG/usr/share/fonts/OTF/
+cp -av OFL.txt README.md $PKG/usr/doc/$PRGNAM-$VERSION/arimo
+
+cd .. && cd $FNTC-$COUSINEVER
+install -m644 fonts/ttf/*.ttf $PKG/usr/share/fonts/TTF/
+install -m644 fonts/otf/*.otf $PKG/usr/share/fonts/OTF/
+cp -av OFL.txt $PKG/usr/doc/$PRGNAM-$VERSION/cousine
+
+cd ..
+
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
+find $PKG/usr/doc/$PRGNAM-$VERSION -type f -exec chmod 0644 {} \+
 
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
 cat $CWD/doinst.sh > $PKG/install/doinst.sh
 
 cd $PKG
-/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
+/sbin/makepkg -l y -c n --remove-rpaths --remove-tmp-rpaths $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
