academic/hp-prime: Updated for version 2.3.1
Signed-off-by: Christoph Willing <chris.willing@slackbuilds.org>

diff --git a/academic/hp-prime/hp-prime.SlackBuild b/academic/hp-prime/hp-prime.SlackBuild
--- a/academic/hp-prime/hp-prime.SlackBuild
+++ b/academic/hp-prime/hp-prime.SlackBuild
@@ -2,7 +2,7 @@
 
 # Slackware build script for hp-prime
 
-# Copyright 2025 Antonio Leal, Porto Salvo, Oeiras, Portugal
+# Copyright 2025-2026 Antonio Leal, Porto Salvo, Oeiras, Portugal
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -26,43 +26,156 @@ cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=hp-prime
 VERSION=${VERSION:-2.3.1}
-BUILD=${BUILD:-3}
+BUILD=${BUILD:-4}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
+ARCHS="i386,x86_64"
+VINHO=wine-10.0
 
-case "$( uname -m )" in
-  x86_64) ARCH=x86_64; TARBALL="HP_Prime_Virtual_Calculator_x64_2025_01_31.exe"  ;;
-    i?86) ARCH=i586; TARBALL="HP_Prime_Virtual_Calculator_2025_01_31.exe"  ;;
-       *) echo "Package for $(uname -m) architecture is not available." ; exit 1 ;;
-esac
+TMP=${TMP:-/tmp/SBo}
+PKG=$TMP/package-$PRGNAM
+OUTPUT=${OUTPUT:-/tmp}
+
+if [ -z "$ARCH" ]; then
+ case "$(uname -m)" in
+  i?86) ARCH=i586 ;;
+  arm*) ARCH=arm ;;
+  *) ARCH=$(uname -m) ;;
+ esac
+fi
 
 if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
   echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
   exit 0
 fi
 
-TMP=${TMP:-/tmp/SBo}
-PKG=$TMP/package-$PRGNAM
-OUTPUT=${OUTPUT:-/tmp}
+OPENGL=${OPENGL@L}
+if [ "${OPENGL:-yes}" = "yes" ]; then
+ do_opengl="with"
+else
+ do_opengl="without"
+fi
+
+BUILD_ARCH="$ARCH-slackware-linux"
+SLKCFLAGS="-O2"
+
+case "$ARCH" in
+ arm)
+  BUILD_ARCH="$ARCH-slackware-linux-gnueabi"
+  ;;
+ i?86)
+  # -Os was -O2, fix for:
+  # https://bugs.winehq.org/show_bug.cgi?id=42406
+  # https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78911
+  # https://bugs.gentoo.org/613128
+  SLKCFLAGS="-Os -march=$ARCH -mtune=i686"
+  WINE32="yes"
+  TARBALL="HP_Prime_Virtual_Calculator_2025_01_31.exe"
+  ;;
+ x86_64)
+  SLKCFLAGS="-O2 -fPIC"
+  WINE64="yes"
+  TARBALL="HP_Prime_Virtual_Calculator_x64_2025_01_31.exe"
+  ;;
+esac
+
+MULTILIB=${MULTILIB@L}
+if [[ "$ARCH" != "x86_64" && "$MULTILIB" = "yes" ]]; then
+  echo "Cannot build for multilib on non-64bit systems."
+  exit 1
+elif [[ "$ARCH" = "x86_64" && "$MULTILIB" = "yes"  ]]; then
+  WINETMP="$( mktemp -d $TMP/wine-test-XXXXXX )"
+  echo "int main(void) {; return(0); }" > "$WINETMP/test.c"
+  gcc -m32 "$WINETMP/test.c" -o /dev/null >/dev/null 2>&1 && WINE32TEST=${WINE32TEST:-yes}
+  rm -rf "$WINETMP"
+  if [[ $WINE32TEST = "yes" ]]; then
+    ARCHS="x86_64"
+    WINE32="yes"
+  else
+    echo "MULTILIB was requested, however the multilib test has failed."
+    echo "Have the compat32 libraries been installed?"
+    echo "Please see README.MULTILIB"
+    exit 1
+  fi
+fi
 
 set -e
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
-rm -rf $PRGNAM-$VERSION
-mkdir $PRGNAM-$VERSION
-cd $PRGNAM-$VERSION
-
+rm -rf $VINHO
+tar xvf $CWD/$VINHO.tar.xz
+cd $VINHO
 chown -R root:root .
 find -L . \
  \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
-  -o -perm 511 \) -exec chmod 755 {} \; -o \
+ -o -perm 511 \) -exec chmod 755 {} \; -o \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
-  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
+ -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
 
-mkdir -p $PKG/usr/src/hp-prime
-cp $CWD/$TARBALL $PKG/usr/src/hp-prime/
+# Fix for flex
+patch -p1 --verbose < $CWD/flex.patch
+# WriteCopy Fix
+patch -p1 < $CWD/writecopy.patch
+# Fix path of opencl headers.
+sed 's|OpenCL/opencl.h|CL/opencl.h|g' -i configure*
+
+if [ "$WINE64" = "yes" ]; then
+  wine64="--with-wine64=../wine64"
+  mkdir wine64
+  cd wine64
+
+  LDFLAGS="-L/usr/lib64 -ldl" \
+  CFLAGS="$SLKCFLAGS" \
+  CXXFLAGS="$SLKCFLAGS" \
+    ../configure \
+     --prefix=/opt/hp-prime \
+     --enable-win64 \
+     --enable-archs=$ARCHS \
+     --with-x \
+     --with-gnutls \
+     --${do_opengl}-opengl \
+     --program-prefix= \
+     --program-suffix= \
+     --disable-tests \
+     --build=$BUILD_ARCH
+  make depend
+  make
+  make install DESTDIR=$PKG
+  cd ..
+fi
+
+if [ "$WINE32" = "yes" ]; then
+  mkdir wine32
+  cd wine32
+  export PKG_CONFIG_PATH="/usr/lib/pkgconfig:$PKG_CONFIG_PATH"
+
+  LDFLAGS="-L/usr/lib -ldl" \
+  CFLAGS="$SLKCFLAGS" \
+  CXXFLAGS="$SLKCFLAGS" \
+    ../configure \
+     $wine64 \
+     --prefix=/opt/hp-prime \
+     --with-x \
+     --with-gnutls \
+     --${do_opengl}-opengl \
+     --program-prefix=testpre32 \
+     --program-suffix=testsuf32 \
+     --disable-tests \
+     --build=$BUILD_ARCH
+  make depend
+  make
+  make install DESTDIR=$PKG
+  cd ..
+fi
+
+find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
+ | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
+
+# Place HP Prime Binaries in-place
+cd ..
+cp $CWD/$TARBALL $PKG/opt/hp-prime/
 
 mkdir -p $PKG/usr/bin
 install -Dvm755 $CWD/hp-prime $PKG/usr/bin/hp-prime
