graphics/flpsed: Updated for version 0.7.3, new maintainer.

diff --git a/graphics/flpsed/flpsed.SlackBuild b/graphics/flpsed/flpsed.SlackBuild
--- a/graphics/flpsed/flpsed.SlackBuild
+++ b/graphics/flpsed/flpsed.SlackBuild
@@ -1,11 +1,13 @@
 #!/bin/sh
 
 # Slackware build script for flpsed
-# Written by Jack Maddox <jackmaddox@gmail.com>
-# Based on http://slackbuilds.org/template.SlackBuild
+# Originally written by Jack Maddox <jackmaddox@gmail.com>
+# Currently maintained by B. Watson <yalhcru@gmail.com>
+
+# Licensed under the WTFPL. See http://www.wtfpl.net/txt/copying/ for details.
 
 PRGNAM=flpsed
-VERSION=${VERSION:-0.6.1}
+VERSION=${VERSION:-0.7.3}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 
@@ -51,6 +53,20 @@ find -L . \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
  -exec chmod 644 {} \;
 
+# Allow building with SBo fltk13 package or Pat's extra/fltk on -current
+# (or 14.2, when it's released).
+if [ "$( fltk-config --api-version 2>/dev/null )" = "1.3" ]; then
+  FLTKCONFIG="$( which fltk-config )"
+else
+  FLTKCONFIG="$( which fltk13-config )"
+fi
+
+if [ -z "$FLTKCONFIG" ]; then
+  echo "$0: can't find fltk-config for fltk version 1.3.x" 1>&2
+  exit 1
+fi
+
+FLTKCONFIG="$FLTKCONFIG" \
 CFLAGS="$SLKCFLAGS" \
 CXXFLAGS="$SLKCFLAGS" \
 ./configure \
@@ -62,17 +78,12 @@ CXXFLAGS="$SLKCFLAGS" \
   --build=$ARCH-slackware-linux
 
 make
-make install DESTDIR=$PKG
+make install-strip DESTDIR=$PKG
 
-find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
-  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
-
-find $PKG/usr/man -type f -exec gzip -9 {} \;
+gzip -9 $PKG/usr/man/man1/$PRGNAM.1
 
 mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a \
-  README INSTALL COPYING AUTHORS NEWS \
-  $PKG/usr/doc/$PRGNAM-$VERSION
+cp -a README INSTALL COPYING AUTHORS NEWS $PKG/usr/doc/$PRGNAM-$VERSION
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
 mkdir -p $PKG/usr/share/applications
