games/z26: Updated for version 2.13

diff --git a/games/z26/z26.SlackBuild b/games/z26/z26.SlackBuild
--- a/games/z26/z26.SlackBuild
+++ b/games/z26/z26.SlackBuild
@@ -29,6 +29,9 @@ if [ "$ARCH" = "i486" ]; then
   SLKCFLAGS="-O2 -march=i486 -mtune=i686"
 elif [ "$ARCH" = "i686" ]; then
   SLKCFLAGS="-O2 -march=i686 -mtune=i686"
+elif [ "$ARCH" = "x86_64" ]; then
+  echo "Can't build on x86_64, sorry"
+  exit 1
 fi
 
 set -e
@@ -62,4 +65,4 @@ mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
 
 cd $PKG
-/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
+/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
