system/cantarell-fonts: New Maintainer and updated to version 0.311
Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/system/cantarell-fonts/cantarell-fonts.SlackBuild b/system/cantarell-fonts/cantarell-fonts.SlackBuild
--- a/system/cantarell-fonts/cantarell-fonts.SlackBuild
+++ b/system/cantarell-fonts/cantarell-fonts.SlackBuild
@@ -2,6 +2,7 @@
 #
 # Slackware build script for cantarell-fonts.
 #
+# Copyright (c) 2026 Vijay Marcel
 # Copyright 2015-2023  Edinaldo P. Silva, Rio de Janeiro, Brazil
 # All rights reserved.
 #
@@ -10,6 +11,10 @@
 #
 # 1. Redistributions of this script must retain the above copyright
 #    notice, this list of conditions and the following disclaimer.
+#
+# 2. Redistributions in binary form must reproduce the above copyright
+#    notice, this list of conditions and the following disclaimer in
+#    the documentation and/or other materials provided with the distribution.
 #
 #  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
 #  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
@@ -25,16 +30,12 @@
 cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=cantarell-fonts
-VERSION=${VERSION:-0.303.1}
+VERSION=${VERSION:-0.311}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
-
 ARCH=noarch
 
-# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
-# the name of the created package would be, and then exit. This information
-# could be useful to other scripts.
 if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
   echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
   exit 0
@@ -45,12 +46,15 @@ PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
 
 set -e
+trap 'echo "$0 FAILED at line $LINENO!" | tee $OUTPUT/error-${PRGNAM}.log' ERR
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
 rm -rf $PRGNAM-$VERSION
-tar xvf $CWD/$PRGNAM-$VERSION.tar.?z
+mkdir -pv $PRGNAM-$VERSION
+ar x $CWD/fonts-cantarell_0.311-3_all.deb
+tar -xvf data.tar.xz -C $PRGNAM-$VERSION
 cd $PRGNAM-$VERSION
 chown -R root:root .
 find -L . \
@@ -59,23 +63,13 @@ find -L . \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
   -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
 
-export CFLAGS="$SLKCFLAGS"
-export CXXFLAGS="$SLKCFLAGS"
-meson build -D useprebuilt=true
-meson compile -C build
-DESTDIR=$PKG meson install -C build
+mkdir -pv $PKG/usr/share/metainfo
+cp -av $TMP/$PRGNAM-$VERSION/usr/share/metainfo/org.gnome.cantarell.metainfo.xml $PKG/usr/share/metainfo/org.gnome.cantarell.metainfo.xml
+mkdir -pv $PKG/usr/share/fonts/OTF
+cp -av $TMP/$PRGNAM-$VERSION/usr/share/fonts/opentype/cantarell/* $PKG/usr/share/fonts/OTF
 
-find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
-  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
-
-mkdir -p $PKG/usr/share/metainfo
-cp -a $PKG/usr/local/share/metainfo/org.gnome.cantarell.metainfo.xml $PKG/usr/share/metainfo/org.gnome.cantarell.metainfo.xml
-mkdir -p $PKG/usr/share/fonts/TTF/cantarell
-cp -a $PKG/usr/local/share/fonts/cantarell/* $PKG/usr/share/fonts/TTF/cantarell/
-rm -rf $PKG/usr/local
-
-mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp COPYING NEWS README.md $PKG/usr/doc/$PRGNAM-$VERSION
+mkdir -pv $PKG/usr/doc/$PRGNAM-$VERSION
+cp -av $TMP/$PRGNAM-$VERSION/usr/share/doc/fonts-cantarell/{copyright,README.md.gz} $PKG/usr/doc/$PRGNAM-$VERSION
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
 mkdir -p $PKG/install
