network/drifnet: Updated for version 0.1.6_p20090401.
Signed-off-by: Robby Workman <rworkman@slackbuilds.org>

diff --git a/network/driftnet/driftnet.SlackBuild b/network/driftnet/driftnet.SlackBuild
--- a/network/driftnet/driftnet.SlackBuild
+++ b/network/driftnet/driftnet.SlackBuild
@@ -3,16 +3,14 @@
 # Written by JK Wood <joshuakwood@gmail.com>
 
 PRGNAM=driftnet
-VERSION=0.1.6
-BUILD=${BUILD:-2}
+VERSION=0.1.6_p20090401
+BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 
-# Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
     i?86) ARCH=i486 ;;
     arm*) ARCH=arm ;;
-    # Unless $ARCH is already set, use uname -m for all other archs:
        *) ARCH=$( uname -m ) ;;
   esac
 fi
@@ -36,12 +34,14 @@ else
   LIBDIRSUFFIX=""
 fi
 
+set -e
+
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
-cd $TMP || exit 1
+cd $TMP
 rm -rf $PRGNAM-$VERSION
-tar -xzvf $CWD/$PRGNAM-$VERSION.tar.gz || exit 1
-cd $PRGNAM-$VERSION || exit 1
+tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
+cd $PRGNAM-$VERSION
 chown -R root:root .
 find . \
  \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
@@ -49,31 +49,24 @@ find . \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
  -exec chmod 644 {} \;
 
+# Clean up building with libpng14 - thanks Gentoo!
+sed -i -e 's:png_set_gray_1_2_4_to_8:png_set_expand_gray_1_2_4_to_8:' png.c
  
 CFLAGS="$SLKCFLAGS" \
 CXXFLAGS="$SLKCFLAGS" \
 ARCH="$ARCH" \
-make || exit 1
+make
 
 # This screwy program has no make install, so we get to do things the hard way.
 mkdir -p $PKG/usr/bin $PKG/usr/man/man1
-cp $TMP/$PRGNAM-$VERSION/driftnet $PKG/usr/bin
-cp $TMP/$PRGNAM-$VERSION/driftnet.1 $PKG/usr/man/man1
-
-find $PKG | xargs file | grep -e "executable" -e "shared object"| grep ELF | \
-  cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
-
-(
-  cd $PKG/usr/man || exit 1
-  find . -type f -exec gzip -9 {} \;
-  for i in $(find . -type l); do ln -s $(readlink $i).gz $i.gz ; rm $i ; done
-)
+cp -a driftnet $PKG/usr/bin
+strip --strip-unneeded $PKG/usr/bin/driftnet
+gzip -9c driftnet.1 > $PKG/usr/man/man1/driftnet.1.gz
 
 mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
 cp -a CHANGES COPYING CREDITS README TODO \
   $PKG/usr/doc/$PRGNAM-$VERSION
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
-find $PKG/usr/doc -name "Makefile" -exec rm {} \;
 find $PKG/usr/doc -type f -exec chmod 644 {} \;
 
 mkdir -p $PKG/install
@@ -81,4 +74,3 @@ cat $CWD/slack-desc > $PKG/install/slack-desc
 
 cd $PKG
 /sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
-
