games/golly: Updated for version 4.3.
Signed-off-by: B. Watson <urchlay@slackware.uk>

Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/games/golly/golly.SlackBuild b/games/golly/golly.SlackBuild
--- a/games/golly/golly.SlackBuild
+++ b/games/golly/golly.SlackBuild
@@ -24,6 +24,7 @@
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #  Updated for golly 2.6 -- the source directory structure got changed a bit too!
 
+# 20240813 bkw: update for v4.3.
 # 20230822 bkw: update for v4.2. note that REQUIRES changed to wxWidgets, as
 # this version needs wxWidgets-3.1 or greater.
 # 20211118 bkw: BUILD=2, new-style icons, tweak .desktop file.
@@ -41,7 +42,7 @@
 cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=golly
-VERSION=${VERSION:-4.2}
+VERSION=${VERSION:-4.3}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
@@ -95,7 +96,7 @@ find -L .  -perm /111 -a \! -perm 755 -a -exec chmod 755 {} \+ -o \
 WXDEF="$( /bin/ls /usr/lib$LIBDIRSUFFIX/wx/config/gtk*unicode*3.2 | head -1 )"
 WXCONF="${WXCONF:-$WXDEF}"
 if [ -z "$WXCONF" ]; then
-  echo "Can't find wxGTK3-3.0.x, install wxWidgets or set WXCONF in environment." 1>&2
+  echo "Can't find wxGTK3-3.2.x, install wxWidgets or set WXCONF in environment." 1>&2
   exit 1
 fi
 
