games/golly: Updated for version 4.2.
Signed-off-by: B. Watson <urchlay@slackware.uk>

Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/games/golly/golly.SlackBuild b/games/golly/golly.SlackBuild
--- a/games/golly/golly.SlackBuild
+++ b/games/golly/golly.SlackBuild
@@ -24,6 +24,8 @@
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #  Updated for golly 2.6 -- the source directory structure got changed a bit too!
 
+# 20230822 bkw: update for v4.2. note that REQUIRES changed to wxWidgets, as
+# this version needs wxWidgets-3.1 or greater.
 # 20211118 bkw: BUILD=2, new-style icons, tweak .desktop file.
 # 20201112 bkw: update for v4.0. Which adds a python3 dep.
 # 20181211 bkw:
@@ -39,8 +41,8 @@
 cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=golly
-VERSION=${VERSION:-4.0}
-BUILD=${BUILD:-2}
+VERSION=${VERSION:-4.2}
+BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
 
@@ -88,31 +90,35 @@ find -L .  -perm /111 -a \! -perm 755 -a -exec chmod 755 {} \+ -o \
         \! -perm /111 -a \! -perm 644 -a -exec chmod 644 {} \+
 
 # 20181211 bkw: wxPython and wxGTK3 both install a /usr/bin/wx-config
-# symlink. We *need* wxGTK3, so don't trust the symlink as it points to
-# whichever was most recently installed.
-WXDEF="$( /bin/ls /usr/lib$LIBDIRSUFFIX/wx/config/gtk*unicode*3.0 | head -1 )"
+# symlink. We *need* wxWidgets-3.2.x, so don't trust the symlink as it points
+# to whichever was most recently installed.
+WXDEF="$( /bin/ls /usr/lib$LIBDIRSUFFIX/wx/config/gtk*unicode*3.2 | head -1 )"
 WXCONF="${WXCONF:-$WXDEF}"
 if [ -z "$WXCONF" ]; then
-  echo "Can't find wxGTK3-3.0.x, install wxGTK3 or set WXCONF in environment." 1>&2
+  echo "Can't find wxGTK3-3.0.x, install wxWidgets or set WXCONF in environment." 1>&2
   exit 1
 fi
 
 SHAREDIR=/usr/share/games/$PRGNAM
 
-# 20201112 bkw: golly is the only project I ever heard of that
-# migrated from autotools back to a plain Makefile. So we can't build
-# versions < 4.0 any more, sorry.
-# We don't enable sound because it needs a proprietary non-free
-# library called irrKlang, which we don't (yet?) have on SBo and
-# I'm in no hurry to add.
+# 20230822 bkw: golly is the only project I ever heard of that
+# migrated from autotools back to a plain Makefile. I approve, but it
+# means we can't build versions < 4.0 any more, sorry.
+# 20230822 bkw: in 4.2, sound support uses SDL, so we can enable it.
+# Note to self: to test whether sound works, Scripts -> Lua -> credits.lua
+# plays a song while showing scrolling credits.
 cd gui-wx
 cat > local-gtk.mk <<EOF
 WX_CONFIG = $WXCONF
 PYTHON = python3
 ENABLE_PERL = 1
+ENABLE_SOUND = 1
 CXXFLAGS = $SLKCFLAGS
 GOLLYDIR = $SHAREDIR
 EOF
+
+# 20230822 bkw: don't trust this.
+echo > local-gtk-template.mk
 
 make -f makefile-gtk
 
