graphics/SweetHome3D: Version bump to 7.2
Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/graphics/SweetHome3D/SweetHome3D.SlackBuild b/graphics/SweetHome3D/SweetHome3D.SlackBuild
--- a/graphics/SweetHome3D/SweetHome3D.SlackBuild
+++ b/graphics/SweetHome3D/SweetHome3D.SlackBuild
@@ -4,7 +4,7 @@
 
 # Copyright 2011 by Giovanne Castro, Campinas, Sao Paulo, Brazil <giovannefc@ig.com.br>
 # Copyright 2012-2018 by Edward Koenig, Vancouver, Washington, USA <kingbeowulf@linuxgalaxy.org>
-# Copyright 2023 Jeremy Hansen <jebrhansen+SBo -at- gmail.com>
+# Copyright 2023 Jeremy Hansen <jebrhansen+SBo@gmail.com>
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -27,7 +27,7 @@
 cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=SweetHome3D
-VERSION=${VERSION:-7.1}
+VERSION=${VERSION:-7.2}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
@@ -40,9 +40,6 @@ if [ -z "$ARCH" ]; then
   esac
 fi
 
-# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
-# the name of the created package would be, and then exit. This information
-# could be useful to other scripts.
 if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
   echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
   exit 0
@@ -54,16 +51,13 @@ OUTPUT=${OUTPUT:-/tmp}
 
 if [ "$ARCH" = "i586" ]; then
   TARGET="x86"
-  LIBDIRSUFFIX=""
 elif [ "$ARCH" = "i686" ]; then
   TARGET="x86"
-  LIBDIRSUFFIX=""
 elif [ "$ARCH" = "x86_64" ]; then
   TARGET="x64"
-  LIBDIRSUFFIX="64"
 else
-  SLKCFLAGS="-O2"
-  LIBDIRSUFFIX=""
+  echo "$ARCH is unsupported."
+  exit 1
 fi
 
 set -e
@@ -76,6 +70,13 @@ cd $PKG/opt
 rm -rf $PRGNAM-$VERSION
 tar xvf $CWD/$PRGNAM-$VERSION-linux-$TARGET.tgz
 ln -s $PRGNAM-$VERSION $PRGNAM
+
+find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
+  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
+
+# Make ELF libraries/binaries executable to prevent sbopkglint failure
+find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
+  | cut -f 1 -d : | xargs chmod +x 2> /dev/null || true
 
 mkdir -p $PKG/usr/bin
 install -D -m 755 $CWD/$PRGNAM $PKG/usr/bin/$PRGNAM
