network/ipcalc-ng: New maintainer.
Signed-off-by: B. Watson <urchlay@slackware.uk>

Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/network/ipcalc-ng/ipcalc-ng.SlackBuild b/network/ipcalc-ng/ipcalc-ng.SlackBuild
--- a/network/ipcalc-ng/ipcalc-ng.SlackBuild
+++ b/network/ipcalc-ng/ipcalc-ng.SlackBuild
@@ -2,31 +2,25 @@
 
 # Slackware build script for ipcalc-ng
 
-# Copyright 2024, Alexander Verbovetsky, Moscow, Russia
-# All rights reserved.
-#
-# Redistribution and use of this script, with or without modification, is
-# permitted provided that the following conditions are met:
-#
-# 1. Redistributions of this script must retain the above copyright
-#    notice, this list of conditions and the following disclaimer.
-#
-#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
-#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
-#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
-#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
-#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
-#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
-#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
-#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
-#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
-#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+# Original author: Alexander Verbovetsky, Moscow, Russia
+# Modified & now maintained by B. Watson <urchlay@slackware.uk>.
+
+# Licensed under the WTFPL. See http://www.wtfpl.net/txt/copying/ for details.
+
+# 20250924 bkw: v1.0.3, BUILD=2
+# - take over maintenance.
+# - relicense as WTFPL.
+# - add COPYING to doc dir.
+# - script cleanup.
+# - remove libmaxminddb from REQUIRES, since I couldn't make it work.
+# - mention GeoIP as an optional dep.
+# - add prebuilt man page, get rid of rubygem-ronn and its deps.
 
 cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=ipcalc-ng
 VERSION=${VERSION:-1.0.3}
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
 
@@ -73,12 +67,26 @@ rm -rf ipcalc-$VERSION
 tar xvf $CWD/ipcalc-$VERSION.tar.gz
 cd ipcalc-$VERSION
 chown -R root:root .
-find -L . \
- \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
-  -o -perm 511 \) -exec chmod 755 {} \; -o \
- \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
-  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
+find -L .  -perm /111 -a \! -perm 755 -a -exec chmod 755 {} + -o \
+        \! -perm /111 -a \! -perm 644 -a -exec chmod 644 {} +
 
+# 20250925 bkw: undocumented, for use by me.
+if [ "${MAKEMAN:-no}" != "yes" ]; then
+  # don't build the man page (no -D to disable it, have to sed).
+  sed -i '/^ronn/,/^$/d' meson.build
+  echo "==== Using prebuilt man page."
+else
+  if ! ronn --version >/dev/null; then
+    echo "!!!! Can't build man page, install rubygem-ronn and its deps"
+    exit 0
+  fi
+  echo "==== Building man page."
+fi
+
+# 20250925 bkw: it only builds with one of libmaxminddb or GeoIP,
+# not both. I couldn't actually get libmaxminddb to work, so I
+# removed it from REQUIRES and disabled it below. GeoIP is
+# optional, autodetected, documented in README.
 mkdir build
 cd build
   CFLAGS="$SLKCFLAGS" \
@@ -91,26 +99,37 @@ cd build
     --mandir=/usr/man \
     --prefix=/usr \
     --sysconfdir=/etc \
-    -Duse_maxminddb=enabled \
+    -Duse_maxminddb=disabled \
     -Dstrip=true
   "${NINJA:=ninja}"
   DESTDIR=$PKG $NINJA install
 cd ..
 
-rm -f $PKG/{,usr/}lib${LIBDIRSUFFIX}/*.la
+if [ -e build/ipcalc.1 ]; then
+  echo "==== Copying new man page to \$CWD"
+  cp build/ipcalc.1 $CWD
+fi
 
-find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
-  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
+# 20250925 bkw: include a man page symlink named after the package
+# name, to help out new users.
+MAN1=$PKG/usr/man/man1
+mkdir -p $MAN1
+gzip -9c < $CWD/ipcalc.1 > $MAN1/ipcalc.1.gz
+ln -s ipcalc.1.gz $MAN1/$PRGNAM.1.gz
 
-find $PKG/usr/man -type f -exec gzip -9 {} \;
-for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
+# 20250925 bkw: did we build with GeoIP support? Can't use ldd because
+# it gets dlopen'ed at runtime. This works:
+WITHGEO=WITHOUT
+strings $PKG/usr/bin/ipcalc | grep -q libGeoIP.so && WITHGEO=WITH
 
-mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a NEWS README.md $PKG/usr/doc/$PRGNAM-$VERSION
-cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
+PKGDOC=$PKG/usr/doc/$PRGNAM-$VERSION
+mkdir -p $PKGDOC
+cp -a COPYING NEWS README.md $PKGDOC
+cat $CWD/$PRGNAM.SlackBuild > $PKGDOC/$PRGNAM.SlackBuild
 
 mkdir -p $PKG/install
-cat $CWD/slack-desc > $PKG/install/slack-desc
+sed "s,@WITHGEO@,$WITHGEO," \
+  $CWD/slack-desc > $PKG/install/slack-desc
 
 cd $PKG
 /sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
