multimedia/ffmpeg: Updated for version 0.8.7.
Signed-off-by: Robby Workman <rworkman@slackbuilds.org>

diff --git a/multimedia/ffmpeg/ffmpeg.SlackBuild b/multimedia/ffmpeg/ffmpeg.SlackBuild
--- a/multimedia/ffmpeg/ffmpeg.SlackBuild
+++ b/multimedia/ffmpeg/ffmpeg.SlackBuild
@@ -7,8 +7,8 @@
 # Modified by Heinz Wiesinger <pprkut@liwjatan.org>
 
 PRGNAM=ffmpeg
-VERSION=${VERSION:-0.6.1}
-BUILD=${BUILD:-2}
+VERSION=${VERSION:-0.8.7}
+BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 
 if [ -z "$ARCH" ]; then
@@ -38,6 +38,15 @@ else
   LIBDIRSUFFIX=""
 fi
 
+# environment sanity checks
+TEXI2HTML=$(which texi2html 2>/dev/null)
+
+if [ "$TEXI2HTML" = "" ]; then
+  echo "Could not find texi2html! Please make sure to have tetex or texlive installed"
+  echo "and that texi2html is in PATH."
+  exit 1
+fi
+
 # --enable-runtime-cpu is meant for libswscale only and
 # has no influence on the other parts of ffmpeg so there's
 # not really a point in bothering
@@ -47,91 +56,28 @@ PKGARCH=$(uname -m)_custom
 # Unfortunately ffmpeg's configure doesn't support --enable-feature=yes
 # syntax, so we have to do it the complicated way :/
 
-if [ "${DC1394:-no}" = "no" ]; then
-  libdc1394=""
-else
-  libdc1394="--enable-libdc1394"
-fi
+libcelt=""    ; [ "${CELT:-no}" != "no" ]         && libcelt="--enable-libcelt"
+libdc1394=""  ; [ "${DC1394:-no}" != "no" ]       && libdc1394="--enable-libdc1394"
+dirac_slow="" ; [ "${DIRAC:-no}" != "no" ]        && dirac_slow="--enable-libdirac"
+libfrei0r=""  ; [ "${FREI0R:-no}" != "no" ]       && libfrei0r="--enable-frei0r"
+libgsm=""     ; [ "${GSM:-no}" != "no" ]          && libgsm="--enable-libgsm"
+libopencv=""  ; [ "${OPENCV:-no}" != "no" ]       && libopencv="--enable-libopencv"
+librtmp=""    ; [ "${RTMP:-no}" != "no" ]         && librtmp="--enable-librtmp"
+dirac_fast="" ; [ "${SCHROEDINGER:-no}" != "no" ] && dirac_fast="--enable-libschroedinger"
+libspeex=""   ; [ "${SPEEX:-no}" != "no" ]        && libspeex="--enable-libspeex"
+libvpx=""     ; [ "${VPX:-no}" != "no" ]          && libvpx="--enable-libvpx"
+libxvid=""    ; [ "${XVID:-no}" != "no" ]         && libxvid="--enable-libxvid"
 
-if [ "${DIRAC:-no}" = "no" ]; then
-  dirac_slow=""
-else
-  dirac_slow="--enable-libdirac"
-fi
+opencore_amr="" ; [ "${OPENCORE:-no}" != "no" ] && \
+  opencore_amr="--enable-libopencore-amrnb --enable-libopencore-amrwb"
+libfaac=""      ; [ "${FAAC:-no}" != "no" ]     && \
+  { libfaac="--enable-libfaac" ; non_free="--enable-nonfree" ; }
+openjpeg=""     ; [ "${JP2:-no}" != "no" ]      && \
+  { openjpeg="--enable-libopenjpeg" ; \
+    SLKCFLAGS="$SLKCFLAGS -I/usr/include/openjpeg-1.4" ; }
 
-if [ "${FAAC:-no}" = "no" ]; then
-  libfaac=""
-else
-  libfaac="--enable-libfaac"
-  non_free="--enable-nonfree"
-fi
-
-if [ "${FAAD:-no}" = "no" ]; then
-  libfaad=""
-else
-  libfaad="--enable-libfaad"
-fi
-
-if [ "${GSM:-no}" = "no" ]; then
-  libgsm=""
-else
-  libgsm="--enable-libgsm"
-fi
-
-if [ "${LAME:-yes}" = "yes" ]; then
-  mp3lame="--enable-libmp3lame"
-else
-  mp3lame=""
-fi
-
-if [ "${JP2:-no}" = "no" ]; then
-  openjpeg=""
-else
-  openjpeg="--enable-libopenjpeg"
-  SLKCFLAGS="$SLKCFLAGS -I/usr/include/openjpeg-1.4"
-fi
-
-if [ "${OPENCORE:-no}" = "no" ]; then
-    opencore_amr=""
-else
-    opencore_amr="--enable-libopencore-amrnb --enable-libopencore-amrwb"
-fi
-
-if [ "${RTMP:-no}" = "no" ]; then
-  librtmp=""
-else
-  librtmp="--enable-librtmp"
-fi
-
-if [ "${SCHROEDINGER:-no}" = "no" ]; then
-  dirac_fast=""
-else
-  dirac_fast="--enable-libschroedinger"
-fi
-
-if [ "${SPEEX:-no}" = "no" ]; then
-  libspeex=""
-else
-  libspeex="--enable-libspeex"
-fi
-
-if [ "${VPX:-no}" = "no" ]; then
-  libvpx=""
-else
-  libvpx="--enable-libvpx"
-fi
-
-if [ "${X264:-yes}" = "yes" ]; then
-  libx264="--enable-libx264"
-else
-  libx264=""
-fi
-
-if [ "${XVID:-no}" = "no" ]; then
-  libxvid=""
-else
-  libxvid="--enable-libxvid"
-fi
+mp3lame="--enable-libmp3lame" ; [ "${LAME:-yes}" != "yes" ] && mp3lame=""
+libx264="--enable-libx264"    ; [ "${X264:-yes}" != "yes" ] && libx264=""
 
 set -e
 
@@ -163,13 +109,11 @@ CXXFLAGS="$SLKCFLAGS" \
   --enable-swscale \
   --enable-x11grab \
   --enable-avfilter \
-  --enable-avfilter-lavf \
   --arch=$ARCH \
   $openjpeg \
   $libdc1394 \
   $mp3lame \
   $libfaac \
-  $libfaad \
   $libxvid \
   $libx264 \
   $libspeex \
@@ -179,20 +123,23 @@ CXXFLAGS="$SLKCFLAGS" \
   $libgsm \
   $libvpx \
   $librtmp \
-  $opencore_amr
+  $opencore_amr \
+  $libopencv \
+  $libfrei0r \
+  $libcelt
 
 make
 make install DESTDIR=$PKG
 make install-man DESTDIR=$PKG
 
-find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
-  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
+find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | \
+  grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
 
 find $PKG/usr/man -type f -exec gzip -9 {} \;
 
 mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a Changelog* COPYING* CREDITS* INSTALL* MAINTAINERS* \
-  README* doc/TODO* doc/*.txt $PKG/usr/doc/$PRGNAM-$VERSION
+cp -a COPYING* CREDITS INSTALL LICENSE MAINTAINERS README RELEASE \
+  VERSION doc/TODO* doc/*.txt $PKG/usr/doc/$PRGNAM-$VERSION
 cp -a doc/*.html $PKG/usr/doc/$PRGNAM-$VERSION
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
