libraries/libnet: Updated for version 1.1.2.1

diff --git a/libraries/libnet/libnet.SlackBuild b/libraries/libnet/libnet.SlackBuild
--- a/libraries/libnet/libnet.SlackBuild
+++ b/libraries/libnet/libnet.SlackBuild
@@ -1,15 +1,18 @@
 #!/bin/sh
-set -e
 
-# Slackbuild for lidnet
+# Slackbuild for libnet
 # Joe Rozner livinded@deabytes.net
 # Wednesday 08/22/2007
 
+# Modified by Roberto Neri <rneri@libero.it> to
+# - remove CVS directories from source tree and miscellaneous script cleanup
+
 PRGNAM=libnet
-VERSION=1.1.2.1
+VERSION=${VERSION:-1.1.2.1}
 ARCH=${ARCH:-i486}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
+
 CWD=$(pwd)
 TMP=${TMP:-/tmp/SBo}
 PKG=$TMP/package-$PRGNAM
@@ -19,45 +22,44 @@ if [ "$ARCH" = "i486" ]; then
   SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  elif [ "$ARCH" = "i686" ]; then
   SLKCFLAGS="-O2 -march=i686 -mtune=i686"
+ elif [ "$ARCH" = "x86_64" ]; then
+  SLKCFLAGS="-O2 -fPIC"
 fi
+
+set -e
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
 rm -rf $PRGNAM
-tar xvf $CWD/$PRGNAM.tar.gz
+tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
 cd $PRGNAM
 chown -R root:root .
 chmod -R u+w,go+r,a-s .
+find . -type d -name CVS | sort -r | xargs rm -rf
 
 CFLAGS="$SLKCFLAGS" \
   ./configure \
   --prefix=/usr \
   --sysconfdir=/etc \
-  --localstatedir=/var
+  --localstatedir=/var \
+  --build=$ARCH-slackware-linux
 
 make
-make install DESTDIR=$PKG
+make install-strip DESTDIR=$PKG
 
-( cd $PKG
-  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
-  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
-)
-
-mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a README VERSION doc/* $PKG/usr/doc/$PRGNAM-$VERSION
-cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
-rm -rf $PKG/usr/doc/$PRGNAM-$VERSION/CVS
-
-mv $PKG/usr/doc/$PRGNAM-$VERSION/man/ $PKG/usr/
-rm -rf $PKG/usr/man/CVS # WTH is this?
+cp -a doc/man $PKG/usr/
 ( cd $PKG/usr/man
   find . -type f -exec gzip -9 {} \;
   for i in $(find . -type l) ; do ln -s $(readlink $i).gz $i.gz ; rm $i ; done
 )
 
+mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
+cp -a README VERSION doc/html $PKG/usr/doc/$PRGNAM-$VERSION
+cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
+
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
 
 cd $PKG
-/sbin/makepkg -l y -c n $TMP/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
+/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
