system/fantasque-sans-mono: New maintainer
Signed-off-by: Christoph Willing <chris.willing@slackbuilds.org>

Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/system/fantasque-sans-mono/fantasque-sans-mono.SlackBuild b/system/fantasque-sans-mono/fantasque-sans-mono.SlackBuild
--- a/system/fantasque-sans-mono/fantasque-sans-mono.SlackBuild
+++ b/system/fantasque-sans-mono/fantasque-sans-mono.SlackBuild
@@ -2,6 +2,7 @@
 
 # Slackware build script for fantasque-sans-mono
 
+# Copyright 2026 Vijay Marcel,India
 # Copyright 2019 klorophatu
 # All rights reserved.
 #
@@ -11,7 +12,11 @@
 # 1. Redistributions of this script must retain the above copyright
 #    notice, this list of conditions and the following disclaimer.
 #
-#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
+# 2. Redistributions in binary form must reproduce the above copyright
+#    notice, this list of conditions and the following disclaimer in
+#    the documentation and/or other materials provided with the distribution.
+#
+#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
 #  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 #  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
 #  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
@@ -29,12 +34,9 @@ VERSION=${VERSION:-1.8.0}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
-
 ARCH=noarch
+SRCA=FantasqueSansMono-Normal
 
-# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
-# the name of the created package would be, and then exit. This information
-# could be useful to other scripts.
 if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
   echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
   exit 0
@@ -45,33 +47,32 @@ PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
 
 set -eu
+trap 'echo "$0 FAILED at line $LINENO!" | tee -a $OUTPUT/error-${PRGNAM}.log' ERR
 
 rm -rf $PKG
-mkdir -p $TMP $PKG $OUTPUT
+mkdir -pv $TMP $PKG $OUTPUT
 
 cd $TMP
-rm -rf $PRGNAM-$VERSION
-mkdir $PRGNAM-$VERSION
-
+rm -rf $SRCA
+mkdir -pv $PRGNAM-$VERSION
+tar xvf $CWD/$SRCA.tar.gz -C $PRGNAM-$VERSION
 cd $PRGNAM-$VERSION
-unzip $CWD/FantasqueSansMono-Normal.zip
-
 chown -R root:root .
 find -L . \
  \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
-  -o -perm 511 \) -exec chmod 755 {} \; -o \
+  -o -perm 511 \) -exec chmod 755 {} \+ -o \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
-  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
+  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \+
 
-mkdir -p $PKG/usr/share/fonts/OTF
-cp -a OTF/*.otf $PKG/usr/share/fonts/OTF
+mkdir -pv $PKG/usr/share/fonts/OTF
+cp -av OTF/*.otf $PKG/usr/share/fonts/OTF
 
-mkdir -p $PKG/usr/share/fonts/TTF
-cp -a TTF/*.ttf $PKG/usr/share/fonts/TTF
+mkdir -pv $PKG/usr/share/fonts/TTF
+cp -av TTF/*.ttf $PKG/usr/share/fonts/TTF
 
-mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a LICENSE.txt $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a *.md $PKG/usr/doc/$PRGNAM-$VERSION
+mkdir -pv $PKG/usr/doc/$PRGNAM-$VERSION
+cp -av LICENSE.txt $PKG/usr/doc/$PRGNAM-$VERSION
+cp -av *.md $PKG/usr/doc/$PRGNAM-$VERSION
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
 mkdir -p $PKG/install
@@ -79,4 +80,4 @@ cat $CWD/slack-desc > $PKG/install/slack-desc
 cat $CWD/doinst.sh > $PKG/install/doinst.sh
 
 cd $PKG
-/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
+/sbin/makepkg -l y -c n --remove-rpaths --remove-tmp-rpaths $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
