multimedia/jlscp: Fix jdk detection.
Signed-off-by: B. Watson <yalhcru@gmail.com>

Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/multimedia/jlscp/jlscp.SlackBuild b/multimedia/jlscp/jlscp.SlackBuild
--- a/multimedia/jlscp/jlscp.SlackBuild
+++ b/multimedia/jlscp/jlscp.SlackBuild
@@ -4,6 +4,10 @@
 
 # Written by klaatu@member.fsf.org
 
+# 20220331 bkw: Modified by SlackBuilds.org: fail if JAVA_HOME not set
+# and can't be set from profile.d script. This avoid creating a /jre
+# in the package root.
+
 cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=jlscp
@@ -13,9 +17,6 @@ TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
 ARCH=noarch
 
-# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
-# the name of the created package would be, and then exit. This information
-# could be useful to other scripts.
 if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
   echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
   exit 0
@@ -36,9 +37,21 @@ cd $PRGNAM-$VERSION
 chown -R root:root .
 find -L . \
  \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 -o -perm 511 \) \
- -exec chmod 755 {} \; -o \
+ -exec chmod 755 {} \+ -o \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
- -exec chmod 644 {} \;
+ -exec chmod 644 {} \+
+
+if [ -z "$JAVA_HOME" ]; then
+  source /etc/profile.d/zulu-openjdk8.sh
+fi
+
+if [ -z "$JAVA_HOME" ]; then
+  cat <<EOF
+*** No JDK found. Install zulu-openjdk8 or another *jdk package and
+*** try again.
+EOF
+  exit 1
+fi
 
 # here is the install, such as it is
 mkdir -p $PKG/$JAVA_HOME/jre/lib/ext
