games/zsnes: Updated for version 1.51

diff --git a/games/zsnes/zsnes.SlackBuild b/games/zsnes/zsnes.SlackBuild
--- a/games/zsnes/zsnes.SlackBuild
+++ b/games/zsnes/zsnes.SlackBuild
@@ -26,7 +26,7 @@ VERSION=1.51
 ZSNESSRC=151src
 ZSNESDIR=_1_51
 ARCH=${ARCH:-i486}
-BUILD=${BUILD:-3}
+BUILD=${BUILD:-4}
 TAG=${TAG:-_SBo}
 
 CWD=$(pwd)
@@ -39,7 +39,8 @@ if [ "$ARCH" = "i486" ]; then
 elif [ "$ARCH" = "i686" ]; then
   SLKCFLAGS="-O2 -march=i686 -mtune=i686"
 elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2 -fPIC"
+  printf "\n  Error: $PRGNAM won't compile on $ARCH \n \n"
+  exit 1
 fi
 
 set -e
