audio/guitarix: Fix building on i486.
Due to changes in gcc-5.3.0, guitarix fails to build without SSE.

Signed-off-by: David Spencer <idlemoor@slackbuilds.org>

diff --git a/audio/guitarix/guitarix.SlackBuild b/audio/guitarix/guitarix.SlackBuild
--- a/audio/guitarix/guitarix.SlackBuild
+++ b/audio/guitarix/guitarix.SlackBuild
@@ -37,6 +37,14 @@
 # - Add WEBKIT=no option.
 # - Remove LV2=no option from README (but not from script).
 
+# 20160329 dbs:
+# - Updated for Slackware-14.2.  Forced -msse in SLKCFLAGS.
+#   This just won't build without SSE on 32 bit gcc-5.3.0 :(
+#     xmmintrin.h:857:1: error: inlining failed in call to always_inline
+#     ‘void _MM_SET_EXCEPTION_STATE(unsigned int)’: target specific option mismatch
+#   Patch 0003-fix-build-even-for-gcc4.8.patch doesn't fix it, and there
+#   are no further fixes upstream at this time.
+
 # Modified version released under the WTFPL, for details see
 # http://www.wtfpl.net/txt/copying/
 
@@ -59,10 +67,10 @@ PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
 
 if [ "$ARCH" = "i486" ]; then
-  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
+  SLKCFLAGS="-O2 -march=i486 -mtune=i686 -msse"
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "i686" ]; then
-  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
+  SLKCFLAGS="-O2 -march=i686 -mtune=i686 -msse"
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "x86_64" ]; then
   SLKCFLAGS="-O2 -fPIC"
@@ -109,8 +117,8 @@ if [ "${PATCH:-no}" = "yes" ]; then
   done
 fi
 
-# allow building non-SSE package on SSE host
-[ "${SSE:-yes}" = "no" ] && EXTRAOPT="$EXTRAOPT --disable-sse"
+# Disallow building non-SSE package
+[ "${SSE:-yes}" = "no" ] && echo "Building a non-SSE package is not supported." && exit 1
 
 LIBDIR="/usr/lib${LIBDIRSUFFIX}"
 ./waf configure \
