desktop/kdmtheme: Updated for version 1.2.2

diff --git a/desktop/kdmtheme/kdmtheme.SlackBuild b/desktop/kdmtheme/kdmtheme.SlackBuild
--- a/desktop/kdmtheme/kdmtheme.SlackBuild
+++ b/desktop/kdmtheme/kdmtheme.SlackBuild
@@ -1,7 +1,6 @@
 #!/bin/sh
 # 
 # SlackBuild script for kdmtheme
-# Written by Michiel van Wessem (BP{k}) <michiel@slackbuilds.org>
 
 # Copyright  2007 Michiel van Wessem (http://michielvwessem.wordpress.com)
 # All rights reserved.
@@ -23,13 +22,12 @@
 # OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 # ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-set -e 
-
 PRGNAM=kdmtheme
-VERSION=1.1.3
+VERSION=1.2.2
 ARCH=${ARCH:-i486}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
+
 CWD=$(pwd)
 TMP=${TMP:-/tmp/SBo}
 PKG=$TMP/package-$PRGNAM
@@ -43,21 +41,33 @@ elif [ "$ARCH" = "i686" ]; then
     SLKCFLAGS="-O2 -march=i686 -mtune=i686"
 fi
 
+set -e # Exit on errors
+
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 rm -rf $TMP/$PRGNAM-$VERSION
 cd $TMP 
-tar -xjvf $CWD/$PRGNAM-$VERSION.tar.bz2
+tar xvf $CWD/$PRGNAM-$VERSION.tar.bz2
 cd $PRGNAM-$VERSION
 chown -R root:root .
-chmod -R u+w,go+r-w,a-s .
+find . \
+ \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
+ -exec chmod 755 {} \; -o \
+ \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
+ -exec chmod 644 {} \;
+
+# Patch borken configure that insists on automake-1.7.
+# Patch by Gohanz (http://www.slacky.eu)
+ACVER=$(whereis aclocal- 2>&1|sed -e 's#.*bin/aclocal-\([0-9.]*\).*#\1#')
+sed -i "s/am__api_version=\"1.7\"/am__api_version=\"$ACVER\"/" configure
+
+KDEPREF=$(kde-config --prefix) || true
 
 CFLAGS="$SLKCFLAGS" \
 CXXFLAGS="$SLKCFLAGS" \
-./configure --prefix=/opt/kde \
-  --disable-debug \
-  --program-prefix="" \
-  --program-suffix=""
+./configure \
+  --prefix=$KDEPREF \
+  --disable-debug 
 
 make
 make install-strip DESTDIR=$PKG
