audio/klick: Updated for version 0.14.2.
Signed-off-by: B. Watson <urchlay@slackware.uk>

Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/audio/klick/klick.SlackBuild b/audio/klick/klick.SlackBuild
--- a/audio/klick/klick.SlackBuild
+++ b/audio/klick/klick.SlackBuild
@@ -6,6 +6,11 @@
 
 # Licensed under the WTFPL. See http://www.wtfpl.net/txt/copying/ for details.
 
+# 20240908 bkw:
+# - update for v0.14.2, new homepage (github).
+# - remove LIBLO=no since builds fail without it and it's already
+#   listed in REQUIRES.
+
 # 20211129 bkw: BUILD=2
 # - fix build on -current. see Makefile.
 # - autodetect rubberband and liblo.
@@ -19,8 +24,8 @@
 cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=klick
-VERSION=${VERSION:-0.12.2}
-BUILD=${BUILD:-2}
+VERSION=${VERSION:-0.14.2}
+BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
 
@@ -43,19 +48,22 @@ OUTPUT=${OUTPUT:-/tmp}
 
 if [ "$ARCH" = "i586" ]; then
   SLKCFLAGS="-O2 -march=i586 -mtune=i686"
-  LIBDIRSUFFIX=""
 elif [ "$ARCH" = "i686" ]; then
   SLKCFLAGS="-O2 -march=i686 -mtune=i686"
-  LIBDIRSUFFIX=""
 elif [ "$ARCH" = "x86_64" ]; then
   SLKCFLAGS="-O2 -fPIC"
-  LIBDIRSUFFIX="64"
 else
   SLKCFLAGS="-O2"
-  LIBDIRSUFFIX=""
 fi
 
 set -e
+
+if ! pkg-config --exists liblo; then
+  cat <<EOF
+$0: builds without liblo no longer possible as of klick-0.14.2.
+EOF
+  exit 1
+fi
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
@@ -64,17 +72,17 @@ rm -rf $PRGNAM-$VERSION
 tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
 cd $PRGNAM-$VERSION
 chown -R root:root .
-find -L .  -perm /111 -a \! -perm 755 -a -exec chmod 755 {} \+ -o \
-        \! -perm /111 -a \! -perm 644 -a -exec chmod 644 {} \+
+find -L .  -perm /111 -a \! -perm 755 -a -exec chmod 755 {} + -o \
+        \! -perm /111 -a \! -perm 644 -a -exec chmod 644 {} +
 
 RUBBERBAND=${RUBBERBAND:-yes}
-LIBLO=${LIBLO:-yes}
 pkg-config --exists rubberband || RUBBERBAND="no"
-pkg-config --exists liblo || LIBLO="no"
 
 # 20211129 bkw: wrote a Makefile because the SConstruct is too old
 # for scons-4.0.1 and I hate scons anyway.
-make -f $CWD/Makefile RUBBERBAND=$RUBBERBAND OSC=$LIBLO SLKCFLAGS="$SLKCFLAGS"
+# 20240908 bkw: updated Makefile for 0.14.2. didn't even try scons, I
+# still hate it.
+make -f $CWD/Makefile RUBBERBAND=$RUBBERBAND OSC=yes SLKCFLAGS="$SLKCFLAGS"
 
 mkdir -p $PKG/usr/bin $PKG/usr/share/$PRGNAM/samples
 install -oroot -groot -s -m0755 $PRGNAM $PKG/usr/bin
@@ -89,13 +97,12 @@ mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
 cp -a COPYING NEWS README doc/manual.html $PKG/usr/doc/$PRGNAM-$VERSION
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
-L=no; R=no
+R=no
 objdump -p $PKG/usr/bin/$PRGNAM > otmp
-grep -q 'NEEDED.*liblo' otmp && L=yes
 grep -q 'NEEDED.*librubberband' otmp && R=yes
 
 mkdir -p $PKG/install
-sed -e "s,@L@,$L," -e "s,@R@,$R," $CWD/slack-desc > $PKG/install/slack-desc
+sed -e "s,@R@,$R," $CWD/slack-desc > $PKG/install/slack-desc
 
 # Only add capability stuff if not disabled:
 if [ "${SETCAP:-yes}" = "yes" ]; then
