network/rdma-core: Updated for version 65.0
Signed-off-by: Christoph Willing <chris.willing@slackbuilds.org>

Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/network/rdma-core/rdma-core.SlackBuild b/network/rdma-core/rdma-core.SlackBuild
--- a/network/rdma-core/rdma-core.SlackBuild
+++ b/network/rdma-core/rdma-core.SlackBuild
@@ -2,6 +2,7 @@
 
 # Slackware build script for rdma-core
 
+# Copyright 2026 Vijay Marcel, India
 # Copyright 2019-2023 GUAN Xin from Beijing
 # All rights reserved.
 #
@@ -10,6 +11,10 @@
 #
 # 1. Redistributions of this script must retain the above copyright
 #    notice, this list of conditions and the following disclaimer.
+#
+# 2. Redistributions in binary form must reproduce the above copyright
+#    notice, this list of conditions and the following disclaimer in
+#    the documentation and/or other materials provided with the distribution.
 #
 #  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
 #  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
@@ -25,7 +30,7 @@
 cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=rdma-core
-VERSION=${VERSION:-54.0}
+VERSION=${VERSION:-65.0}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
@@ -47,21 +52,18 @@ TMP=${TMP:-/tmp/SBo}
 PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
 
-if [ "$ARCH" = "i586" ]; then
-  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
-  LIBDIRSUFFIX=""
-elif [ "$ARCH" = "i686" ]; then
-  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
+if [ "$ARCH" = "i586" -o "$ARCH" = "i686" ]; then
+  SLKCFLAGS="-march=$ARCH -mtune=i686 -pipe -O2 -fPIC"
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2 -fPIC"
+  SLKCFLAGS="-march=x86-64 -mtune=generic -pipe -O2 -fPIC"
   LIBDIRSUFFIX="64"
 else
-  SLKCFLAGS="-O2"
-  LIBDIRSUFFIX=""
+  echo "This SlackBuild will not run on $ARCH" && exit 1
 fi
 
 set -e
+trap 'echo "$0 FAILED at line $LINENO!" | tee $OUTPUT/error-${PRGNAM}.log' ERR
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
@@ -72,47 +74,41 @@ cd $PRGNAM-$VERSION
 chown -R root:root .
 find -L . \
  \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
-  -o -perm 511 \) -exec chmod 755 {} \; -o \
+  -o -perm 511 \) -exec chmod 755 {} \+ -o \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
-  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
+  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \+
 
-patch -p1 --verbose <$CWD/optional_pandoc.patch
-
-mkdir -p build
-cd build
-  cmake \
+cmake -B build -S "$TMP/$PRGNAM-$VERSION" \
     -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
     -DCMAKE_INSTALL_PREFIX=/usr \
-    -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib$LIBDIRSUFFIX \
+    -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib${LIBDIRSUFFIX} \
     -DCMAKE_INSTALL_LOCALSTATEDIR:PATH=/var/run \
     -DCMAKE_INSTALL_MANDIR:PATH=/usr/man \
     -DCMAKE_INSTALL_SYSCONFDIR:PATH=/etc \
     -DCMAKE_INSTALL_INITDDIR:PATH=/etc/rc.d/init.d \
+    -DCMAKE_INSTALL_PERLDIR=/usr/share/perl5/vendor_perl \
     -DCMAKE_INSTALL_DOCDIR:PATH=/usr/doc/$PRGNAM-$VERSION \
-    -DCMAKE_BUILD_TYPE=Release \
-    ..
-  make
-  make install DESTDIR=$PKG
-cd ..
+    -DNO_MAN_PAGES=ON \
+    -DENABLE_VALGRIND=OFF \
+    -DCMAKE_BUILD_TYPE=Release
+
+cmake --build build
+DESTDIR=$PKG cmake --install build
 
 # Remove systemd stuff
 (cd $PKG/usr/lib && rm -r udev/rules.d/60-srp_daemon.rules systemd)
 
 find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
-  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
+  | cut -f 1 -d : | xargs strip --strip-unneeded --remove-section=.comment --remove-section=.note 2> /dev/null || true
 
-find $PKG/usr/man -type f -exec gzip -9 {} \;
-for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
-
-mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a \
-  COPYING.* \
-  $PKG/usr/doc/$PRGNAM-$VERSION
+mkdir -pv $PKG/usr/doc/$PRGNAM-$VERSION
+cp -av COPYING.* MAINTAINERS README.md $PKG/usr/doc/$PRGNAM-$VERSION
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
 cat $CWD/doinst.sh > $PKG/install/doinst.sh
+
 ( cd $PKG
   find etc -type f -regextype posix-extended -not -regex "^etc/libibverbs.d/.*" \
     -exec mv {} {}.new \; \
@@ -121,4 +117,4 @@ cat $CWD/doinst.sh > $PKG/install/doinst.sh
 )
 
 cd $PKG
-/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
+/sbin/makepkg -l y -c n --remove-rpaths --remove-tmp-rpaths $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
