development/qt-creator-llvm: Updated for version 7.0_4a75f114.
Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/development/qt-creator-llvm/qt-creator-llvm.SlackBuild b/development/qt-creator-llvm/qt-creator-llvm.SlackBuild
--- a/development/qt-creator-llvm/qt-creator-llvm.SlackBuild
+++ b/development/qt-creator-llvm/qt-creator-llvm.SlackBuild
@@ -2,7 +2,7 @@
 
 # Slackware build script for LLVM/Clang tools for Qt Creator
 
-# Copyright 2018 Andrzej Telszewski, Szczecin
+# Copyright 2019 Andrzej Telszewski, Szczecin
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -23,10 +23,8 @@
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 PRGNAM=qt-creator-llvm
-VERSION=${VERSION:-5.0.1_427ad76}
-VERSION_CLAZY=${VERSION_CLAZY:-427ad7689ac65bc4106c0a420c1165cc57f1eef7}
-VERSION_LLVM=$( echo $VERSION | cut -f1 -d_ )
-BUILD=${BUILD:-2}
+VERSION=${VERSION:-7.0_4a75f114}
+BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 
 if [ -z "$ARCH" ]; then
@@ -62,18 +60,8 @@ rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
 rm -rf $PRGNAM-$VERSION
-tar xvf $CWD/llvm-$VERSION_LLVM.src.tar.xz
-mv llvm-$VERSION_LLVM.src $PRGNAM-$VERSION
+tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
 cd $PRGNAM-$VERSION
-
-tar xvf $CWD/cfe-$VERSION_LLVM.src.tar.xz -C tools
-mv tools/cfe-$VERSION_LLVM.src tools/clang
-
-tar xvf $CWD/clang-tools-extra-$VERSION_LLVM.src.tar.xz -C tools/clang/tools
-mv tools/clang/tools/clang-tools-extra-$VERSION_LLVM.src tools/clang/tools/extra
-
-tar xvf $CWD/clazy-$VERSION_CLAZY.tar.gz -C tools/clang/tools/extra
-mv tools/clang/tools/extra/clazy-$VERSION_CLAZY tools/clang/tools/extra/clazy
 
 chown -R root:root .
 find -L . \
@@ -82,8 +70,17 @@ find -L . \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
   -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
 
-# Apply patches found in Qt Creator source tree.
-git apply --whitespace=fix $CWD/patches/*.patch
+# Exceptionally, copy the docs before the build starts.
+# This can save you quite some time in a case of a missing doc file.
+mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION/{clang,clang-tools-extra,clazy}
+cp -a CODE_OWNERS.TXT CREDITS.TXT LICENSE.TXT README.txt RELEASE_TESTERS.TXT \
+  $PKG/usr/doc/$PRGNAM-$VERSION
+cp -a tools/clang/{CODE_OWNERS.TXT,LICENSE.TXT,README.txt} \
+  $PKG/usr/doc/$PRGNAM-$VERSION/clang
+cp -a tools/clang/tools/extra/{CODE_OWNERS.TXT,LICENSE.TXT,README.txt} \
+  $PKG/usr/doc/$PRGNAM-$VERSION/clang-tools-extra
+cp -a tools/clang/tools/extra/clazy/{COPYING-LGPL2.txt,Changelog,HOWTO,README.md} \
+  $PKG/usr/doc/$PRGNAM-$VERSION/clazy
 
 mkdir -p build
 cd build
@@ -102,37 +99,43 @@ cd build
   make install DESTDIR=$PKG
 cd ..
 
-# Remove unnecessary components (reduce the package size).
-VERSION_LLVM_MAJ_MIN=$( echo $VERSION_LLVM | cut -f-2 -d. )
+# Determine "clang" binary version.
+VERSION_CLANG=$( echo $VERSION | cut -f1 -d_ )
+
+if ! [ -x $PKG/usr/libexec/qtcreator/clang/bin/clang-$VERSION_CLANG ]; then
+  VERSION_CLANG=$( echo $VERSION_CLANG | cut -f1 -d. )
+fi
+
+if ! [ -x $PKG/usr/libexec/qtcreator/clang/bin/clang-$VERSION_CLANG ]; then
+  VERSION_CLANG=
+
+  echo "error: Unable to determine \"clang\" binary version."
+  exit 1
+fi
+
+# Remove unnecessary components (reduce package size).
 
 find $PKG/usr/libexec/qtcreator/clang/bin -mindepth 1 -not \( \
-  -name clang -o -name clang-$VERSION_LLVM_MAJ_MIN -o -name llvm-config \) \
+  -name clang -o -name clang-$VERSION_CLANG -o -name llvm-config \) \
   -exec rm {} \;
 
-find $PKG/usr/libexec/qtcreator/clang/lib -name \*.a -not \( \
-  -name libclangTooling.a -o -name libclangIndex.a -o -name libclangFrontend.a -o \
-  -name libclangParse.a -o -name libclangSerialization.a -o -name libclangSema.a -o \
-  -name libclangEdit.a -o -name libclangAnalysis.a -o -name libclangDriver.a -o \
-  -name libclangDynamicASTMatchers.a -o -name libclangASTMatchers.a -o \
-  -name libclangToolingCore.a -o -name libclangAST.a -o -name libclangLex.a -o \
-  -name libclangBasic.a \) \
-  -exec rm {} \;
+# FIXME: Find patience to find out which libs are required by Qt Creator
+#        and then remove the unnecessary ones.
+#find $PKG/usr/libexec/qtcreator/clang/lib -name \*.a -not \( \
+#  -name libclangTooling.a -o -name libclangIndex.a -o -name libclangFrontend.a -o \
+#  -name libclangParse.a -o -name libclangSerialization.a -o -name libclangSema.a -o \
+#  -name libclangEdit.a -o -name libclangAnalysis.a -o -name libclangDriver.a -o \
+#  -name libclangDynamicASTMatchers.a -o -name libclangASTMatchers.a -o \
+#  -name libclangToolingCore.a -o -name libclangAST.a -o -name libclangLex.a -o \
+#  -name libclangBasic.a \) \
+#  -exec rm {} \;
 
-rm -r $PKG/usr/libexec/qtcreator/clang/libexec
-rm -r $PKG/usr/libexec/qtcreator/clang/share
+rm -rf $PKG/usr/libexec/qtcreator/clang/libexec
+rm -rf $PKG/usr/libexec/qtcreator/clang/share
 
 find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
   | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
 
-mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION/{clang,clang-tools-extra,clazy}
-cp -a CODE_OWNERS.TXT CREDITS.TXT LICENSE.TXT README.txt RELEASE_TESTERS.TXT \
-  $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a tools/clang/{CODE_OWNERS.TXT,LICENSE.TXT,README.txt} \
-  $PKG/usr/doc/$PRGNAM-$VERSION/clang
-cp -a tools/clang/tools/extra/{CODE_OWNERS.TXT,LICENSE.TXT,README.txt} \
-  $PKG/usr/doc/$PRGNAM-$VERSION/clang-tools-extra
-cp -a tools/clang/tools/extra/clazy/{COPYING-LGPL2.txt,Changelog,HOWTO,README.md} \
-  $PKG/usr/doc/$PRGNAM-$VERSION/clazy
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
 mkdir -p $PKG/install
