system/slapt-update-service: Updated for version 0.5.4.
Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/system/slapt-update-service/slapt-update-service.SlackBuild b/system/slapt-update-service/slapt-update-service.SlackBuild
--- a/system/slapt-update-service/slapt-update-service.SlackBuild
+++ b/system/slapt-update-service/slapt-update-service.SlackBuild
@@ -2,7 +2,7 @@
 
 # Slackware build script for slapt-update-service
 
-# Copyright 2023 Vijay Marcel
+# Copyright 2023-2025 Vijay Marcel
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -22,10 +22,18 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+# Changelog for slapt-update-service SlackBuild Script
+# ------------------------------------------------------------------------------
+
+# 24/05/2023: Submitted to slackbuilds.org
+# 14/04/2025: updated to version 0.5.4
+
+# -------------------------------------------------------------------------------
+
 cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=slapt-update-service
-VERSION=${VERSION:-0.5.3}
+VERSION=${VERSION:-0.5.4}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
@@ -39,9 +47,6 @@ aarch64*) ARCH=aarch64 ;;
 esac
 fi
 
-# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
-# the name of the created package would be, and then exit. This information
-# could be useful to other scripts.
 if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
   echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
   exit 0
@@ -66,6 +71,7 @@ else
 fi
 
 set -e
+trap 'echo "$0 FAILED at line $LINENO!" | tee -a  $OUTPUT/error-${PRGNAM}.log' ERR
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
@@ -85,13 +91,12 @@ ninja -C build
 DESTDIR=$PKG ninja -C build install
 
 find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
-  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
-
+  | cut -f 1 -d : | xargs strip --strip-unneeded --remove-section=.comment --remove-section=.note 2> /dev/null || true
 
 mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
 mv -v $PKG/usr/share/doc/* $PKG/usr/doc/$PRGNAM-$VERSION
 rm -rvf $PKG/usr/share/doc
-rm -rvf $PKG/usr/doc/slapt-update-service-0.5.3/slapt-update-service/NEWS
+rm -rvf $PKG/usr/doc/$PRGNAM-$VERSION/slapt-update-service/NEWS
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
 mkdir -p $PKG/install
