system/fcron: Update script.
Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/system/fcron/fcron.SlackBuild b/system/fcron/fcron.SlackBuild
--- a/system/fcron/fcron.SlackBuild
+++ b/system/fcron/fcron.SlackBuild
@@ -26,27 +26,13 @@ cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=fcron
 VERSION=${VERSION:-3.3.1}
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
 
 # Select fcron's default user/group
 FCRON_USER=${FCRON_USER:-fcron}
 FCRON_GROUP=${FCRON_GROUP:-fcron}
-
-if ! getent group $FCRON_GROUP >/dev/null;  then
-  echo "Error, the group $FCRON_GROUP does not exist."
-  echo "Create the group and user like this:"
-  echo "  groupadd -g 289 $FCRON_GROUP"
-  echo "  useradd  -u 289 -g $FCRON_GROUP -d /var/spool/fcron -M -s /bin/false $FCRON_USER"
-  exit 1
-fi
-if ! getent passwd $FCRON_USER >/dev/null; then
-  echo "Error, the userid $FCRON_USER does not exist."
-  echo "Create the user like this:"
-  echo "  useradd  -u 289 -g $FCRON_GROUP -d /var/spool/fcron -M -s /bin/false $FCRON_USER"
-  exit 1
-fi
 
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
@@ -62,6 +48,21 @@ fi
 if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
   echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
   exit 0
+fi
+
+# Make sure the fcron default user and group exist
+if ! getent group $FCRON_GROUP >/dev/null;  then
+  echo "Error, the group $FCRON_GROUP does not exist."
+  echo "Create the group and user like this:"
+  echo "  groupadd -g 289 $FCRON_GROUP"
+  echo "  useradd  -u 289 -g $FCRON_GROUP -d /var/spool/fcron -M -s /bin/false $FCRON_USER"
+  exit 1
+fi
+if ! getent passwd $FCRON_USER >/dev/null; then
+  echo "Error, the userid $FCRON_USER does not exist."
+  echo "Create the user like this:"
+  echo "  useradd  -u 289 -g $FCRON_GROUP -d /var/spool/fcron -M -s /bin/false $FCRON_USER"
+  exit 1
 fi
 
 TMP=${TMP:-/tmp/SBo}
