development/openjdk8: Updated for version 8u161.
Signed-off-by: David Spencer <idlemoor@slackbuilds.org>

diff --git a/development/openjdk8/openjdk8.SlackBuild b/development/openjdk8/openjdk8.SlackBuild
--- a/development/openjdk8/openjdk8.SlackBuild
+++ b/development/openjdk8/openjdk8.SlackBuild
@@ -2,7 +2,7 @@
 
 # Slackware build script for OpenJDK
 
-# Copyright 2017 Strahil Yordanov, Sofia, Bulgaria
+# Copyright 2018 Strahil Yordanov, Sofia, Bulgaria
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -23,12 +23,12 @@
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 PRGNAM=openjdk8
-VERSION=${VERSION:-8u151b12}
+VERSION=${VERSION:-8u161}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 
 DVER=1.8.0_$(printf $VERSION | cut -du -f2)
-ICEDTEA=icedtea-3.6.0
+ICEDTEA=icedtea-3.7.0
 
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
@@ -53,6 +53,8 @@ else
 fi
 
 BOOT_JAVA=/usr/lib${LIBDIRSUFFIX}/openjdk
+[ ! -d ${BOOT_JAVA} ] && BOOT_JAVA=${BOOT_JAVA}8
+[ ! -d ${BOOT_JAVA} ] && { echo "Boot java not found"; exit 1; }
 
 set -e
 
@@ -84,7 +86,6 @@ JAVA_HOME=${BOOT_JAVA} PATH=${BOOT_JAVA}/bin:$PATH ../$ICEDTEA/configure \
    --with-hotspot-src-zip="$CWD/hotspot.tar.xz" \
    --disable-docs \
    --disable-downloading
-
 JAVA_HOME=${BOOT_JAVA} PATH=${BOOT_JAVA}/bin:$PATH LOG=trace make
 
 cd $PKG
