games/robotfindskitten: Manually install necessary .nki file.
Signed-off-by: dsomero <xgizzmo@slackbuilds.org>

diff --git a/games/robotfindskitten/robotfindskitten.SlackBuild b/games/robotfindskitten/robotfindskitten.SlackBuild
--- a/games/robotfindskitten/robotfindskitten.SlackBuild
+++ b/games/robotfindskitten/robotfindskitten.SlackBuild
@@ -24,15 +24,13 @@
 
 PRGNAM=robotfindskitten
 VERSION=${VERSION:-2.7182818.701}
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 TAG=${TAG:-_SBo}
 
-# Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
     i?86) ARCH=i486 ;;
     arm*) ARCH=arm ;;
-    # Unless $ARCH is already set, use uname -m for all other archs:
        *) ARCH=$( uname -m ) ;;
   esac
 fi
@@ -56,7 +54,7 @@ else
   LIBDIRSUFFIX=""
 fi
 
-set -e 
+set -e
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
@@ -81,10 +79,14 @@ CXXFLAGS="$SLKCFLAGS" \
   --localstatedir=/var \
   --mandir=/usr/man \
   --infodir=/usr/info \
-  --build=$ARCH-slackware-linux 
+  --build=$ARCH-slackware-linux
 
 make
 make install DESTDIR=$PKG
+
+# make install seems to fail to install the vanilla.nki file to an expected place, so:
+mkdir -p $PKG/usr/share/games/$PRGNAM
+cat ./nki/vanilla.nki > $PKG/usr/share/games/$PRGNAM/vanilla.nki
 
 find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
   | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
