development/google-go-lang: Updated for version 1.21.2.
- Remove test files to reduce package size
  (and make sbopkglint happier).
- Add cgo version check to avoid bootstrap compile on -current

Signed-off-by: Andrew Clemons <andrew.clemons@gmail.com>

Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/development/google-go-lang/google-go-lang.SlackBuild b/development/google-go-lang/google-go-lang.SlackBuild
--- a/development/google-go-lang/google-go-lang.SlackBuild
+++ b/development/google-go-lang/google-go-lang.SlackBuild
@@ -29,7 +29,7 @@
 cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=google-go-lang
-VERSION=${VERSION:-1.21.1}
+VERSION=${VERSION:-1.21.2}
 BOOTSTRAP_VERSION=${BOOTSTRAP_VERSION:-1.19.13}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
@@ -77,63 +77,67 @@ OUTPUT=${OUTPUT:-/tmp}
 set -e
 
 rm -rf $PKG
-mkdir -p $TMP $PKG/usr/lib${LIBDIRSUFFIX}/go${BOOTSTRAP_VERSION} $OUTPUT
-cd $PKG/usr/lib${LIBDIRSUFFIX}/go${BOOTSTRAP_VERSION}
-tar xvf $CWD/go${BOOTSTRAP_VERSION}.src.tar.gz
-cd go
-chown -R root:root .
-find -L . \
- \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
- -o -perm 511 \) -exec chmod 755 {} \; -o \
- \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
- -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
 
-# as of >= go1.5, the cross-compiler does not need to be bootstrap, so the
-# compiler need only be compiled for the host OS, which it detects
-unset GOBIN GOPATH GOOS GOARCH
+CGO_MINOR_VERSION="$(/usr/bin/go version | awk '{ print $3 }' | sed 's/go//' | awk -F. '{ print $2 }')"
+if [[ $CGO_MINOR_VERSION -lt 18 ]] ; then
+  mkdir -p $TMP $PKG/usr/lib${LIBDIRSUFFIX}/go${BOOTSTRAP_VERSION} $OUTPUT
+  cd $PKG/usr/lib${LIBDIRSUFFIX}/go${BOOTSTRAP_VERSION}
+  tar xvf $CWD/go${BOOTSTRAP_VERSION}.src.tar.gz
+  cd go
+  chown -R root:root .
+  find -L . \
+   \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
+   -o -perm 511 \) -exec chmod 755 {} \; -o \
+   \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
+   -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
 
-# Not sure why, but this causes run.bash to fail --rworkman
-unset BASH_ENV
+  # as of >= go1.5, the cross-compiler does not need to be bootstrap, so the
+  # compiler need only be compiled for the host OS, which it detects
+  unset GOBIN GOPATH GOOS GOARCH
 
-# gcc 5+ is go1.4 API, so we'll bootstrap with it
-export GOROOT_BOOTSTRAP="/usr"
+  # Not sure why, but this causes run.bash to fail --rworkman
+  unset BASH_ENV
 
-# Default GOROOT is the parent directory of all.bash,
-# which is the current directory we're in.
-# Defining it here means we can use it below when building
-# shared libraries
-GOROOT="$(pwd)"
-export GOROOT
+  # gcc 5+ is go1.4 API, so we'll bootstrap with it
+  export GOROOT_BOOTSTRAP="/usr"
 
-# The value of GOROOT once the package is installed
-export GOROOT_FINAL="/usr/lib${LIBDIRSUFFIX}/go${BOOTSTRAP_VERSION}/go"
+  # Default GOROOT is the parent directory of all.bash,
+  # which is the current directory we're in.
+  # Defining it here means we can use it below when building
+  # shared libraries
+  GOROOT="$(pwd)"
+  export GOROOT
 
-case "$ARCH" in
-  arm|i?86) export GOMAXPROCS=1 ;;
-esac
+  # The value of GOROOT once the package is installed
+  export GOROOT_FINAL="/usr/lib${LIBDIRSUFFIX}/go${BOOTSTRAP_VERSION}/go"
 
-cd src
+  case "$ARCH" in
+    arm|i?86) export GOMAXPROCS=1 ;;
+  esac
 
-if [[ "${RUN_TEST}" = "true" ]] ; then
-  LC_ALL=C \
-    ./all.bash
-else
-  LC_ALL=C \
-    ./make.bash
+  cd src
+
+  if [[ "${RUN_TEST}" = "true" ]] ; then
+    LC_ALL=C \
+      ./all.bash
+  else
+    LC_ALL=C \
+      ./make.bash
+  fi
+
+  # As of go1.5, golang supports shared libraries, so generate them for use.
+  $GOROOT/bin/go install -buildmode=shared std
+
+  cd ..
+
+  # remove Go build cache
+  rm -rf pkg/obj/go-build/*
+
+  # remove the doc Makefile
+  rm -f doc/Makefile
+
+  mkdir -p $PKG$GOROOT_FINAL
 fi
-
-# As of go1.5, golang supports shared libraries, so generate them for use.
-$GOROOT/bin/go install -buildmode=shared std
-
-cd ..
-
-# remove Go build cache
-rm -rf pkg/obj/go-build/*
-
-# remove the doc Makefile
-rm -f doc/Makefile
-
-mkdir -p $PKG$GOROOT_FINAL
 
 mkdir -p $PKG/usr/lib${LIBDIRSUFFIX}/go${VERSION} $OUTPUT
 cd $PKG/usr/lib${LIBDIRSUFFIX}/go${VERSION}
@@ -154,7 +158,11 @@ unset GOBIN GOPATH GOOS GOARCH
 unset BASH_ENV
 
 # gcc 5+ is go1.4 API, so we'll bootstrap with it
-export GOROOT_BOOTSTRAP="$PKG/usr/lib${LIBDIRSUFFIX}/go${BOOTSTRAP_VERSION}/go"
+if [[ $CGO_MINOR_VERSION -lt 18 ]] ; then
+  export GOROOT_BOOTSTRAP="$PKG/usr/lib${LIBDIRSUFFIX}/go${BOOTSTRAP_VERSION}/go"
+else
+  export GOROOT_BOOTSTRAP="/usr"
+fi
 
 # Default GOROOT is the parent directory of all.bash,
 # which is the current directory we're in.
@@ -183,6 +191,10 @@ fi
 # As of go1.5, golang supports shared libraries, so generate them for use.
 $GOROOT/bin/go install -buildmode=shared std
 
+find $PKG/$GOROOT_FINAL -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
+  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
+find $PKG/$GOROOT_FINAL -type f -name "*.so" -exec chmod +x {} \; 2> /dev/null || true
+
 cd ..
 
 # remove Go build cache
@@ -191,10 +203,16 @@ rm -rf pkg/obj/go-build/*
 # remove the doc Makefile
 rm -f doc/Makefile
 
+# remove tests, nothing needs these at runtime
+find $PKG/$GOROOT_FINAL/src -type d -name "testdata" -exec rm -rf {} +
+find $PKG/$GOROOT_FINAL/src -type f -name "*_test.go" -exec rm -rf {} +
+
 mkdir -p $PKG$GOROOT_FINAL
 
 # remove bootstrap
-rm -rf $PKG/usr/lib$LIBDIRSUFFIX/go$BOOTSTRAP_VERSION
+if [[ $CGO_MINOR_VERSION -lt 18 ]] ; then
+  rm -rf $PKG/usr/lib$LIBDIRSUFFIX/go$BOOTSTRAP_VERSION
+fi
 
 # Put the profile scripts for setting PATH and env variables
 mkdir -p $PKG/etc/profile.d
