network/libnl: Updated for version 1.1

diff --git a/network/libnl/libnl.SlackBuild b/network/libnl/libnl.SlackBuild
--- a/network/libnl/libnl.SlackBuild
+++ b/network/libnl/libnl.SlackBuild
@@ -1,7 +1,6 @@
 #!/bin/sh
 
 # Slackware build script for libnl
-# Written by Andrew Psaltis (ampsaltis@gmail.com)
 
 # Copyright 2007 Andrew Psaltis, Vienna, VA, USA
 # All rights reserved.
@@ -22,14 +21,15 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-set -e
+# Modified by Roberto Neri <rneri@libero.it> to
+# - upgrade to version 1.1 and related script cleanup
 
 PRGNAM=libnl
-VERSION=1.0-pre6
-PKG_VERSION=$(echo $VERSION | tr - _)
+VERSION=1.1
 ARCH=${ARCH:-i486}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
+
 CWD=$(pwd)
 TMP=${TMP:-/tmp/SBo}
 PKG=$TMP/package-$PRGNAM
@@ -43,11 +43,13 @@ elif [ "$ARCH" = "x86_64" ]; then # For BlueWhite64
   SLKCFLAGS="-O2 -fPIC"
 fi
 
+set -e
+
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
 rm -rf $PRGNAM-$SRC_VERSION
-tar xzvf $CWD/$PRGNAM-$VERSION.tar.gz
+tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
 cd $PRGNAM-$VERSION
 chown -R root:root .
 chmod -R u+w,go+r-w,a-s .
@@ -58,22 +60,21 @@ CXXFLAGS="$SLKCFLAGS" \
   --prefix=/usr \
   --sysconfdir=/etc \
   --localstatedir=/var \
-  --with-gnu-ld
+  --with-gnu-ld \
+  --build=$ARCH-slackware-linux
 
 make
 make install DESTDIR=$PKG
 
-( cd $PKG
-  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
-  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
-)
+find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
+  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
 
-mkdir -p $PKG/usr/doc/$PRGNAM-$PKG_VERSION
-cp -a COPYING $PKG/usr/doc/$PRGNAM-$PKG_VERSION
-cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$PKG_VERSION/$PRGNAM.SlackBuild
+mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
+cp -a ChangeLog COPYING $PKG/usr/doc/$PRGNAM-$VERSION
+cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
 
 cd $PKG
-/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$PKG_VERSION-$ARCH-$BUILD$TAG.tgz
+/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
