libraries/libavif: Updated for version 20221216_93035c1.
Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/libraries/libavif/libavif.SlackBuild b/libraries/libavif/libavif.SlackBuild
--- a/libraries/libavif/libavif.SlackBuild
+++ b/libraries/libavif/libavif.SlackBuild
@@ -25,11 +25,11 @@
 cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=libavif
-VERSION=${VERSION:-20220922_d0f2fee}
+VERSION=${VERSION:-20221216_93035c1}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
-GITNAM=${GITNAM:-d0f2fee5e879c003d2860971b41433a69cb2170d}
+GITNAM=${GITNAM:-93035c173c934813b16751872fbe2f535aa7086b}
 
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
@@ -82,11 +82,16 @@ find -L . \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
   -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
 
+
+if [ "$ARCH" = "x86_64" ]; then
+
+echo "Builing for x86_64 Architecture"
+
 cmake -B build -S $TMP/$PRGNAM-$GITNAM  \
     -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
     -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
     -DBUILD_SHARED_LIBS:BOOL=ON \
-    -DAVIF_ENABLE_WERROR:BOOL=OFF \
+    -DAVIF_ENABLE_WERROR:BOOL=ON \
     -DAVIF_CODEC_AOM:BOOL=ON \
     -DAVIF_CODEC_AOM_DECODE:BOOL=ON \
     -DAVIF_CODEC_AOM_ENCODE:BOOL=ON \
@@ -114,6 +119,48 @@ find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | gr
 
 find $PKG/usr/man -type f -exec gzip -9 {} \;
 for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
+
+elif [ "$ARCH" = "i586" ]; then
+
+echo "Builing for x86 Architecture"
+echo "No man pages will be built for x86 architecture, Refer README and changelog for details"
+echo "If you need Man Pages for x86 architecture you have to build pandoc from sources"
+
+cmake -B build -S $TMP/$PRGNAM-$GITNAM  \
+    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
+    -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
+    -DBUILD_SHARED_LIBS:BOOL=ON \
+    -DAVIF_ENABLE_WERROR:BOOL=ON \
+    -DAVIF_CODEC_AOM:BOOL=ON \
+    -DAVIF_CODEC_AOM_DECODE:BOOL=ON \
+    -DAVIF_CODEC_AOM_ENCODE:BOOL=ON \
+    -DAVIF_CODEC_DAV1D:BOOL=ON \
+    -DAVIF_CODEC_LIBGAV1:BOOL=OFF \
+    -DAVIF_CODEC_RAV1E:BOOL=OFF \
+    -DAVIF_CODEC_SVT:BOOL=ON \
+    -DAVIF_BUILD_APPS:BOOL=ON \
+    -DAVIF_BUILD_TESTS:BOOL=OFF \
+    -DAVIF_ENABLE_GTEST:BOOL=OFF \
+    -DAVIF_BUILD_MAN_PAGES:BOOL=OFF \
+    -DCMAKE_INSTALL_PREFIX:PATH=/usr \
+    -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib${LIBDIRSUFFIX} \
+    -DCMAKE_INSTALL_BINDIR:PATH=/usr/bin \
+    -DCMAKE_INSTALL_MANDIR=/usr/man \
+    -DCMAKE_BUILD_TYPE=Release
+
+make -C build
+make -C build install DESTDIR=$PKG
+
+rm -f $PKG/{,usr/}lib${LIBDIRSUFFIX}/*.la
+
+find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
+  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
+
+else
+
+echo "Unsupported Architecture, Aborting the build process ....."
+
+fi
 
 find $PKG -name perllocal.pod -o -name ".packlist" -o -name "*.bs" | xargs rm -f || true
 
