audio/calf: Updated for version 0.90.9.
Signed-off-by: B. Watson <urchlay@slackware.uk>

Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/audio/calf/calf.SlackBuild b/audio/calf/calf.SlackBuild
--- a/audio/calf/calf.SlackBuild
+++ b/audio/calf/calf.SlackBuild
@@ -4,6 +4,11 @@
 
 # Written by B. Watson (urchlay@slackware.uk)
 
+# 20260728 bkw: update for v0.90.9.
+# - Upstream switched to cmake.
+# - 0.90.9 supposedly supports WANT_SSE=OFF, but this causes the build
+#   to fail, so SSE is always enabled.
+
 # 20211204 bkw: BUILD=3, move html docs to subdir.
 # 20200117 bkw: demote lash from required to optional dependency.
 # 20191208 bkw: update for v0.90.3.
@@ -39,8 +44,8 @@
 cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=calf
-VERSION=${VERSION:-0.90.3}
-BUILD=${BUILD:-3}
+VERSION=${VERSION:-0.90.9}
+BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
 
@@ -57,23 +62,37 @@ if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
   exit 0
 fi
 
+# 20260728 bkw: this is necessary because the stupid thing deletes
+# all the *.ttl files from /usr when installing (even though it's
+# smart enough to generate them in DESTDIR/usr).
+if [ -e /usr/bin/calfjackhost ]; then
+  cat <<EOF 1>&2
+*********************************************************
+* calf is already installed. Remove it before building. *
+*********************************************************
+
+This command should do the job:
+
+removepkg calf
+
+EOF
+  exit 1
+fi
+
 TMP=${TMP:-/tmp/SBo}
 PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
 
 if [ "$ARCH" = "i586" ]; then
   SLKCFLAGS="-O2 -march=i586 -mtune=i686"
-  LIBDIRSUFFIX=""
 elif [ "$ARCH" = "i686" ]; then
   SLKCFLAGS="-O2 -march=i686 -mtune=i686"
-  LIBDIRSUFFIX=""
 elif [ "$ARCH" = "x86_64" ]; then
   SLKCFLAGS="-O2 -fPIC"
-  LIBDIRSUFFIX="64"
 else
   SLKCFLAGS="-O2"
-  LIBDIRSUFFIX=""
 fi
+SLKCFLAGS+=" -DNDEBUG"
 
 set -e
 
@@ -81,77 +100,43 @@ rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
 rm -rf $PRGNAM-$VERSION
-tar xvf $CWD/$PRGNAM-$VERSION.tar.?z
+tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
 cd $PRGNAM-$VERSION
 chown -R root:root .
-find -L .  -perm /111 -a \! -perm 755 -a -exec chmod 755 {} \+ -o \
-        \! -perm /111 -a \! -perm 644 -a -exec chmod 644 {} \+
+find . ! -type l    -a \
+  \(     -perm /111 -a ! -perm 755 -a -exec chmod -f 755 {} + \) -o \
+  \(   ! -perm /111 -a ! -perm 644 -a -exec chmod -f 644 {} + \)
 
-autoreconf -if
+# 20260728 bkw: we don't support version 1.5 of the .desktop spec in 15.0:
+sed -i '/^Version/d' calf.desktop
 
-# Note: The build ignores the provided -O2 in the flags (but the
-# -march/-mtune -fPIC stuff is used). If you really want to force
-# it to use -O2 (Slackware default), set FORCE_SLACK_CFLAGS=yes
-# in the environment.
-if [ "${FORCE_SLACK_CFLAGS:-no}" = "yes" ]; then
-  sed -i -e 's/ -O3[^"]*//' configure
-  SSE=no
-fi
+mkdir -p build
+cd build
+  cmake \
+    -DWANT_SSE=ON \
+    -DWANT_EXPERIMENTAL=ON \
+    -DCMAKE_C_FLAGS_RELEASE="$SLKCFLAGS" \
+    -DCMAKE_CXX_FLAGS_RELEASE="$SLKCFLAGS" \
+    -DCMAKE_INSTALL_PREFIX=/usr \
+    -DCMAKE_INSTALL_MANDIR=man \
+    -DCMAKE_INSTALL_DOCDIR=doc/$PRGNAM-$VERSION \
+    -DCMAKE_BUILD_TYPE=Release ..
+  make VERBOSE=1
+  export DESTDIR=$PKG # this has to be in the environment!
+  make install/strip DESTDIR=$PKG
+cd ..
+gzip -9 $PKG/usr/man/man*/*
 
-# Build with SSE support?
-case "${SSE:-auto}" in
-  "yes") SSEOPT="--enable-sse"  ;;
-  "no")  SSEOPT="--disable-sse" ;;
-  *)     grep sse /proc/cpuinfo >/dev/null \
-              && SSEOPT="--enable-sse" \
-              || SSEOPT="--disable-sse" ;;
-esac
-
-echo "=== SSEOPT: $SSEOPT"
-
-# For the slack-desc:
-WITHSSE="without"
-[ "$SSEOPT" = "--enable-sse" ] && WITHSSE="with"
-
-# 20211204 bkw: --docdir and --htmldir accepted and ignored.
-# htmldir on the make command line is also ignored (html docs go to docdir).
-CFLAGS="$SLKCFLAGS" \
-CXXFLAGS="$SLKCFLAGS" \
-./configure \
-  $SSEOPT \
-  --enable-experimental \
-  --prefix=/usr \
-  --libdir=/usr/lib${LIBDIRSUFFIX} \
-  --sysconfdir=/etc \
-  --localstatedir=/var \
-  --mandir=/usr/man \
-  --enable-shared \
-  --disable-static \
-  --with-lv2-dir=/usr/lib${LIBDIRSUFFIX}/lv2 \
-  --build=$ARCH-slackware-linux
-
-make
-make install \
-     DESTDIR=$PKG \
-     docdir=/usr/doc/$PRGNAM-$VERSION/html \
-
-# install-strip is supported, but doesn't work:
-strip $PKG/usr/bin/* $PKG/usr/lib*/{lv2/calf.lv2/calflv2gui.so,calf/calf.so}
-
-gzip $PKG/usr/man/man?/*
-
-mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a AUTHORS COPYING* ChangeLog README TODO $PKG/usr/doc/$PRGNAM-$VERSION
-cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
+PKGDOC=$PKG/usr/doc/$PRGNAM-$VERSION
+mkdir -p $PKGDOC
+cp -a AUTHORS COPYING* ChangeLog README* TODO $PKGDOC
+cat $CWD/$PRGNAM.SlackBuild > $PKGDOC/$PRGNAM.SlackBuild
 
 # This shouldn't be in the package:
 rm -f $PKG/usr/share/icons/hicolor/icon-theme.cache
 
-# Shipped .desktop file doesn't validate, use modified copy:
-cat $CWD/$PRGNAM.desktop > $PKG/usr/share/applications/$PRGNAM.desktop
-
 mkdir -p $PKG/install
-sed "s,@WITHSSE@,$WITHSSE," $CWD/slack-desc > $PKG/install/slack-desc
+cat $CWD/slack-desc > $PKG/install/slack-desc
 cat $CWD/doinst.sh > $PKG/install/doinst.sh
 
 # Only add capability stuff if not disabled:
