system/ttf-arphic-uming: New maintainer
Signed-off-by: Christoph Willing <chris.willing@slackbuilds.org>

Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/system/ttf-arphic-uming/ttf-arphic-uming.SlackBuild b/system/ttf-arphic-uming/ttf-arphic-uming.SlackBuild
--- a/system/ttf-arphic-uming/ttf-arphic-uming.SlackBuild
+++ b/system/ttf-arphic-uming/ttf-arphic-uming.SlackBuild
@@ -2,6 +2,7 @@
 
 # Slackware build script for ttf-arphic-uming
 
+# Copyright 2026 Vijay Marcel,India
 # Copyright 2014 ancker.du <ancker.du@gmail.com>
 # All rights reserved.
 #
@@ -10,6 +11,10 @@
 #
 # 1. Redistributions of this script must retain the above copyright
 #    notice, this list of conditions and the following disclaimer.
+#
+# 2. Redistributions in binary form must reproduce the above copyright
+#    notice, this list of conditions and the following disclaimer in
+#    the documentation and/or other materials provided with the distribution.
 #
 #  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
 #  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
@@ -36,8 +41,8 @@ VERSION=${VERSION:-0.2.20080216.2}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
-
 ARCH=noarch
+SRCNAM=fonts-arphic-uming-debian
 
 if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
   echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
@@ -49,13 +54,14 @@ PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
 
 set -e
+trap 'echo "$0 FAILED at line $LINENO!" | tee $OUTPUT/error-${PRGNAM}.log' ERR
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
-rm -rf $PRGNAM-$VERSION
-tar xvf $CWD/fonts-arphic-uming\_${VERSION}.orig.tar.bz2
-cd $PRGNAM-$VERSION
+rm -rf $SRCNAM-debian-$VERSION-11
+tar xvf $CWD/${SRCNAM}-${VERSION}-11.tar.gz
+cd $SRCNAM-$VERSION-11
 chown -R root:root .
 find -L . \
  \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
@@ -64,26 +70,27 @@ find -L . \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \+
 
 # 20220218 bkw: patch from debian:
-# http://deb.debian.org/debian/pool/main/f/fonts-arphic-uming/fonts-arphic-uming_0.2.20080216.2-11.debian.tar.xz
-patch -p1 < $CWD/30-fix-fontconfig-syntax.patch
+# https://salsa.debian.org/fonts-team/fonts-arphic-uming/-/blob/debian/0.2.20080216.2-11/debian/patches/30-fix-fontconfig-syntax.patch
+# https://salsa.debian.org/fonts-team/fonts-arphic-uming/-/blob/debian/0.2.20080216.2-11/debian/patches/0002-64-arphic-uming.conf-Weaken-priority-and-remove-modi.patch
 
-mkdir -p $PKG/usr/share/fonts/TTF
-cp -a *.ttc $PKG/usr/share/fonts/TTF
+patch --unified --verbose -p1 < $TMP/$SRCNAM-$VERSION-11/debian/patches/30-fix-fontconfig-syntax.patch
+patch --unified --verbose -p1 < $TMP/$SRCNAM-$VERSION-11/debian/patches/0002-64-arphic-uming.conf-Weaken-priority-and-remove-modi.patch
 
-mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a CONTRIBUTERS FONTLOG Font_Comparison_ShanHeiSun_UMing.odt \
-      Font_Comparison_ShanHeiSun_UMing.pdf INSTALL \
-      KNOWN_ISSUES NEWS README README.Bitmap license \
-      $PKG/usr/doc/$PRGNAM-$VERSION
-cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
+mkdir -pv $PKG/usr/share/fonts/TTF
+cp -av *.ttc $PKG/usr/share/fonts/TTF
 
-mkdir -p $PKG/etc/fonts/conf.{d,avail}
-cp -a *.conf $PKG/etc/fonts/conf.avail
+mkdir -pv $PKG/etc/fonts/conf.{d,avail}
+cp -av *.conf $PKG/etc/fonts/conf.avail
 ( cd $PKG/etc/fonts/conf.d && ln -s ../conf.avail/* .)
+
+mkdir -pv $PKG/usr/doc/$PRGNAM-$VERSION
+cp -av CONTRIBUTERS FONTLOG Font_Comparison_ShanHeiSun_UMing.odt \
+      Font_Comparison_ShanHeiSun_UMing.pdf README README.Bitmap license $PKG/usr/doc/$PRGNAM-$VERSION
+cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
 cat $CWD/doinst.sh > $PKG/install/doinst.sh
 
 cd $PKG
-/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
+/sbin/makepkg -l y -c n --remove-rpaths --remove-tmp-rpaths $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
