system/wine-staging: Updated for version 10.0.rc3.
Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/system/wine-staging/wine-staging.SlackBuild b/system/wine-staging/wine-staging.SlackBuild
--- a/system/wine-staging/wine-staging.SlackBuild
+++ b/system/wine-staging/wine-staging.SlackBuild
@@ -33,10 +33,11 @@
 cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=wine-staging
-VERSION=${VERSION:-9.17}
-WINEVERSION=$VERSION
-STAGINGVERSION=$VERSION
+VERSION=${VERSION:-10.0.rc3}
+WINEVERSION=10.0-rc3
+STAGINGVERSION=$WINEVERSION
 ARCHS="i386,x86_64"
+MULTI=""
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
@@ -53,8 +54,29 @@ if [ -z "$ARCH" ]; then
   esac
 fi
 
+MULTILIB=${MULTILIB@L}
+if [[ "$ARCH" != "x86_64" && "$MULTILIB" = "yes" ]]; then
+  echo "Cannot build for multilib on non-64bit systems."
+  exit 1
+elif [[ "$ARCH" = "x86_64" && "$MULTILIB" = "yes"  ]]; then
+  WINETMP="$( mktemp -d $TMP/wine-test-XXXXXX )"
+  echo "int main(void) {; return(0); }" > "$WINETMP/test.c"
+  gcc -m32 "$WINETMP/test.c" -o /dev/null >/dev/null 2>&1 && WINE32TEST=${WINE32TEST:-yes}
+  rm -rf "$WINETMP"
+  if [[ $WINE32TEST = "yes" ]]; then
+    ARCHS="x86_64"
+    WINE32="yes"
+    MULTI="_multilib"
+  else
+    echo "MULTILIB was requested, however the multilib test has failed."
+    echo "Have the compat32 libraries been installed?"
+    echo "Please see README.MULTILIB"
+    exit 1
+  fi
+fi
+
 if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
-  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
+  echo "$PRGNAM-$VERSION$MULTI-$ARCH-$BUILD$TAG.$PKGTYPE"
   exit 0
 fi
 
@@ -87,26 +109,6 @@ case "$ARCH" in
   WINE64="yes"
   ;;
 esac
-
-MULTILIB=${MULTILIB@L}
-if [[ "$ARCH" != "x86_64" && "$MULTILIB" = "yes" ]]; then
-  echo "Cannot build for multilib on non-64bit systems."
-  exit 1
-elif [[ "$ARCH" = "x86_64" && "$MULTILIB" = "yes"  ]]; then
-  WINETMP="$( mktemp -d $TMP/wine-test-XXXXXX )"
-  echo "int main(void) {; return(0); }" > "$WINETMP/test.c"
-  gcc -m32 "$WINETMP/test.c" -o /dev/null >/dev/null 2>&1 && WINE32TEST=${WINE32TEST:-yes}
-  rm -rf "$WINETMP"
-  if [[ $WINE32TEST = "yes" ]]; then
-    ARCHS="x86_64"
-    WINE32="yes"
-  else
-    echo "MULTILIB was requested, however the multilib test has failed."
-    echo "Have the compat32 libraries been installed?"
-    echo "Please see README.MULTILIB"
-    exit 1
-  fi
-fi
 
 set -e
 
@@ -235,4 +237,4 @@ cat $CWD/slack-desc > $PKG/install/slack-desc
 cat $CWD/doinst.sh > $PKG/install/doinst.sh
 
 cd $PKG
-/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
+/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION$MULTI-$ARCH-$BUILD$TAG.$PKGTYPE
