network/yadifa: Updated for version 2.5.3.
Signed-off-by: Dave Woodfall <dave@slackbuilds.org>

Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/network/yadifa/yadifa.SlackBuild b/network/yadifa/yadifa.SlackBuild
--- a/network/yadifa/yadifa.SlackBuild
+++ b/network/yadifa/yadifa.SlackBuild
@@ -25,8 +25,8 @@
 cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=yadifa
-VERSION=${VERSION:-2.4.0}
-VSUFFIX=${VSUFFIX:-9809}
+VERSION=${VERSION:-2.5.3}
+VSUFFIX=${VSUFFIX:-10333}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
@@ -34,17 +34,17 @@ PKGTYPE=${PKGTYPE:-tgz}
 SRCVERSION=$(echo $VERSION-$VSUFFIX | tr _ -)
 
 if ! grep -q "^yadifa:" /etc/group; then
-        echo "$0: Error: $PRGNAM group (yadifa) doesn't exist."
-        echo "$0: Try creating one with:"
-        echo " # groupadd -g 332 yadifa"
-        exit 1
+  echo "$0: Error: $PRGNAM group (yadifa) doesn't exist."
+  echo "$0: Try creating one with:"
+  echo " # groupadd -g 332 yadifa"
+  exit 1
 fi
 
 if ! grep -q "^yadifa:" /etc/passwd; then
-        echo "$0: Error: $PRGNAM user (yadifa) doesn't exist."
-        echo "$0: Try creating one with:"
-        echo " # useradd -u 332 -d /var/lib/yadifa -g yadifa -s /bin/false yadifa"
-        exit 1
+  echo "$0: Error: $PRGNAM user (yadifa) doesn't exist."
+  echo "$0: Try creating one with:"
+  echo " # useradd -u 332 -d /var/lib/yadifa -g yadifa -s /bin/false yadifa"
+  exit 1
 fi
 
 if [ -z "$ARCH" ]; then
@@ -152,8 +152,9 @@ install --mode=644 $CWD/zones.conf   $PKG/etc/yadifa/zones.conf.new
 mkdir -p $PKG/etc/logrotate.d
 install --mode=644 $CWD/yadifa.logrotate $PKG/etc/logrotate.d/yadifa.new
 
-# remove empty file
+# remove empty files
 rm -rf $PKG/etc/yadifa/yadifad.conf
+rm -rf $PKG/etc/yadifa/yakeyrolld.conf
 
 cd $PKG
 /sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
