development/npm2tgz: Tweaked tarball extraction routine
github's archive download system is braindead.

Signed-off-by: Robby Workman <rworkman@slackbuilds.org>

diff --git a/development/npm2tgz/npm2tgz.SlackBuild b/development/npm2tgz/npm2tgz.SlackBuild
--- a/development/npm2tgz/npm2tgz.SlackBuild
+++ b/development/npm2tgz/npm2tgz.SlackBuild
@@ -23,7 +23,16 @@ set -e # Exit on most errors
 rm -fr $TMP/$PRGNAM-$VERSION $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
-tar xvf $CWD/$SRCNAM
+
+if [ -e $CWD/$VERSION.tar.gz ]; then
+  tar xvf $CWD/$SRCNAM
+elif [ -e $CWD/$PRGNAM-$VERSION.tar.gz ]; then
+  tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
+else
+  echo "Source tarball is unusable or not found."
+  exit 1
+fi
+
 cd $PRGNAM-$VERSION
 chown -R root.root .
 find . \
