desktop/maitreya: Updated for version 8.2 + new maintainer
Signed-off-by: Christoph Willing <chris.willing@slackbuilds.org>

diff --git a/desktop/maitreya/maitreya.SlackBuild b/desktop/maitreya/maitreya.SlackBuild
--- a/desktop/maitreya/maitreya.SlackBuild
+++ b/desktop/maitreya/maitreya.SlackBuild
@@ -1,17 +1,43 @@
 #!/bin/bash
-#
+
+# Slackware build script for maitreya 
+
+# Copyright 2026 Vijay Marcel
 # Didier Charles 2011.05.22
 # dcharles@alumni.concordia.ca
 # written with the grateful assistance of the tutorial
 # "Writing A SlackBuild Script" at :
-#  http://www.slackwiki.org/Writing_A_SlackBuild_Script
+# http://www.slackwiki.org/Writing_A_SlackBuild_Script
 # and with the guidance of the templates at:
-#  http://slackbuilds.org/templates/
+# http://slackbuilds.org/templates/
+# All rights reserved.
+#
+# Redistribution and use of this script, with or without modification, is
+# permitted provided that the following conditions are met:
+#
+# 1. Redistributions of this script must retain the above copyright
+#    notice, this list of conditions and the following disclaimer.
+#
+# 2. Redistributions in binary form must reproduce the above copyright
+#    notice, this list of conditions and the following disclaimer in
+#    the documentation and/or other materials provided with the distribution.
+#
+#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
+#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
+#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
+#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
+#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
+#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
+#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
+#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
+#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
+#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=maitreya
-VERSION=${VERSION:-7.0.5}
+SRCNAM=maitreya8
+VERSION=${VERSION:-8.2}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
@@ -33,64 +59,59 @@ if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
   exit 0
 fi
 
-if [ "$ARCH" = "i586" ]; then
-  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
-  LIBDIRSUFFIX=""
-elif [ "$ARCH" = "i686" ]; then
-  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
+if [ "$ARCH" = "i586" -o "$ARCH" = "i686" ]; then
+  SLKCFLAGS="-march=$ARCH -mtune=i686 -pipe -O2 -fPIC"
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2 -fPIC"
+  SLKCFLAGS="-march=x86-64 -mtune=generic -pipe -O2 -fPIC -I/usr/include/vapoursynth"
   LIBDIRSUFFIX="64"
+else
+   echo "This SlackBuild will not run on $ARCH" && exit 1
 fi
 
 set -e
+trap 'echo "$0 FAILED at line $LINENO!" | tee $OUTPUT/error-${PRGNAM}.log' ERR
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
-rm -rf $PRGNAM-$VERSION
-tar xvf $CWD/$PRGNAM-$VERSION.tar.bz2
-cd $PRGNAM-$VERSION
+rm -rf $SRCNAM-$VERSION
+tar xvf $CWD/$SRCNAM-$VERSION.tar.gz
+cd $SRCNAM-$VERSION
 chown -R root:root .
 find -L . \
  \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
-  -o -perm 511 \) -exec chmod 755 {} \; -o \
+  -o -perm 511 \) -exec chmod 755 {} \+ -o \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
-  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
+  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \+
 
+CFLAGS="$SLKCFLAGS" \
+CXXFLAGS="$SLKCFLAGS"  \
 ./configure \
   --prefix=/usr \
   --sysconfdir=/etc \
   --localstatedir=/var \
   --libdir=/usr/lib${LIBDIRSUFFIX} \
+  --with-gnu-ld  \
   --build=$ARCH-slackware-linux
 
-make \
-  fontdir=/usr/share/fonts/TTF \
-  CFLAGS="$SLKCFLAGS" \
-  CXXFLAGS="$SLKCFLAGS"
+make 
+make DESTDIR=$PKG install
 
-make install \
-  fontdir=/usr/share/fonts/TTF \
-  DESTDIR=$PKG
+find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
+  | cut -f 1 -d : | xargs strip --strip-unneeded --remove-section=.comment --remove-section=.note 2> /dev/null || true
 
-( cd $PKG/usr/share/maitreya7/fonts/
-  rm -f MaitreyaSymbols6.ttf
-  ln -s ../../fonts/TTF/MaitreyaSymbols6.ttf
-)
+mkdir -pv $PKG/usr/share/fonts/TTF
+install -Dvm0644 $TMP/$SRCNAM-$VERSION/src/fonts/Saravali.ttf -t $PKG/usr/share/fonts/TTF
 
-mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a INSTALL README $PKG/usr/doc/$PRGNAM-$VERSION
+mkdir -pv $PKG/usr/doc/$PRGNAM-$VERSION
+cp -a AUTHORS README $PKG/usr/doc/$PRGNAM-$VERSION
+install -Dvm0644 $TMP/$SRCNAM-$VERSION/src/fonts/OFL.txt -t $PKG/usr/doc/$PRGNAM-$VERSION
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
-( cd $PKG/usr/doc/$PRGNAM-$VERSION
-  ln -s ../../share/maitreya6/COPYING
-  ln -s ../../share/maitreya6/changelog
-)
 
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
 cat $CWD/doinst.sh > $PKG/install/doinst.sh
 
 cd $PKG
-/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
+/sbin/makepkg -l y -c n --remove-rpaths --remove-tmp-rpaths $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
