python/python3-fonttools: Updated for version 4.49.0.
Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/python/python3-fonttools/python3-fonttools.SlackBuild b/python/python3-fonttools/python3-fonttools.SlackBuild
--- a/python/python3-fonttools/python3-fonttools.SlackBuild
+++ b/python/python3-fonttools/python3-fonttools.SlackBuild
@@ -3,7 +3,7 @@
 # Slackware build script for python3-fonttools
 
 # Copyright 2017-2019,2022 Andrew Clemons, Wellington New Zealand
-# Copyright 2023 Vijay Marcel
+# Copyright 2023-2024 Vijay Marcel
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -27,7 +27,7 @@ cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=python3-fonttools
 SRCNAM=fonttools
-VERSION=${VERSION:-4.42.1}
+VERSION=${VERSION:-4.49.0}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
@@ -56,7 +56,7 @@ elif [ "$ARCH" = "i686" ]; then
   SLKCFLAGS="-march=i686 -mtune=i686 -pipe -O2 -fPIC"
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-march=x86-64 -mtune=generic -pipe  -O2 -fPIC"
+  SLKCFLAGS="-march=x86-64 -mtune=generic -pipe -O2 -fPIC"
   LIBDIRSUFFIX="64"
 else
   SLKCFLAGS="-O2"
@@ -64,6 +64,7 @@ else
 fi
 
 set -e
+trap 'echo "$0 FAILED at line $LINENO!" | tee -a $OUTPUT/error-${PRGNAM}.log' ERR
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
@@ -78,16 +79,16 @@ find -L . \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
   -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
 
-python3 setup.py install --prefix=/usr --root=$PKG --optimize=1
+python3 -m build --wheel --no-isolation
+python3 -m installer --destdir "$PKG" dist/*.whl
 
 find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
-  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
+  | cut -f 1 -d : | xargs strip --strip-unneeded --remove-section=.comment --remove-section=.note 2> /dev/null || true
 
 mv -v  $PKG/usr/share/man $PKG/usr
 rm -rvf $PKG/usr/share
 
 cd Doc
-make singlehtml
 make man
 mv -v $TMP/$SRCNAM-$VERSION/Doc/build/man/fonttools.1  $PKG/usr/man/man1/
 cd ..
@@ -97,7 +98,6 @@ for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; r
 
 mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
 cp -a CONTRIBUTING.md LICENSE.external LICENSE README.rst CODE_OF_CONDUCT.md NEWS.rst $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a $TMP/$SRCNAM-$VERSION/Doc/build/singlehtml  $PKG/usr/doc/$PRGNAM-$VERSION
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 find $PKG/usr/doc/$PRGNAM-$VERSION -type f -exec chmod 0644 {} \+
 
