system/aterm: New maintainer, fix build.
Signed-off-by: B. Watson <urchlay@slackware.uk>

Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/system/aterm/aterm.SlackBuild b/system/aterm/aterm.SlackBuild
--- a/system/aterm/aterm.SlackBuild
+++ b/system/aterm/aterm.SlackBuild
@@ -22,13 +22,24 @@
 # OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 # ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-# Modified by the SlackBuilds.org project
+# 20241010 bkw: v1.0.1, BUILD=2
+# - take over maintenance.
+# - fix build on 64-bit.
+# - make the script actually exit if the binary doesn't get built.
+# - add some patches: compile fix, security, and functionality.
+# - don't install docs/menu with +x files.
+
+# Note: in Slackware 15.0, it compiles and runs, but we get this warning:
+# command.c:1187:13: warning: ‘XKeycodeToKeysym’ is deprecated [-Wdeprecated-declarations]
+# At some point, XKeycodeToKeysym may get removed from Xlib, in which
+# case aterm will be removed from SBo, unless *you* send a patch to
+# fix it (I don't love it enough to do the job myself, sorry).
 
 cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=aterm
 VERSION=${VERSION:-1.0.1}
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
 
@@ -40,9 +51,6 @@ if [ -z "$ARCH" ]; then
   esac
 fi
 
-# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
-# the name of the created package would be, and then exit. This information
-# could be useful to other scripts.
 if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
   echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
   exit 0
@@ -66,6 +74,10 @@ else
   LIBDIRSUFFIX=""
 fi
 
+# 20240713 bkw: this was missing before 1.0.1 build 2. build was
+# failing on x86_64 and nobody ever noticed...
+set -e
+
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
@@ -73,13 +85,16 @@ rm -rf $PRGNAM-$VERSION
 tar xvf $CWD/$PRGNAM-$VERSION.tar.bz2
 cd $PRGNAM-$VERSION
 chown -R root:root .
-find -L . \
- \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
-  -o -perm 511 \) -exec chmod 755 {} \; -o \
- \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
-  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
+find -L .  -perm /111 -a \! -perm 755 -a -exec chmod 755 {} + -o \
+        \! -perm /111 -a \! -perm 644 -a -exec chmod 644 {} +
 
 sed -i 's%<sys/stropts.h>%<sys/ioctl.h>%;s%I_PUSH,%TIOCPKT,%' src/command.c
+
+# patches from https://gitweb.gentoo.org/repo/gentoo.git/tree/x11-terms/aterm
+for i in $CWD/patches/*.diff; do
+  echo "===> applying: $( basename $i )"
+  patch -p1 < $i
+done
 
 CFLAGS="$SLKCFLAGS" \
 CXXFLAGS="$SLKCFLAGS" \
@@ -94,19 +109,14 @@ CXXFLAGS="$SLKCFLAGS" \
 
 make
 make install DESTDIR=$PKG
+strip $PKG/usr/bin/$PRGNAM
+gzip $PKG/usr/man/man1/$PRGNAM.1
 
-find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
-  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
-
-find $PKG/usr/man -type f -exec gzip -9 {} \;
-for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
-
-mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a ChangeLog INSTALL doc/* $PKG/usr/doc/$PRGNAM-$VERSION
-for i in Makefile Makefile.in aterm.1 ;
-  do rm $PKG/usr/doc/$PRGNAM-$VERSION/$i ;
-done
-cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
+PKGDOC=$PKG/usr/doc/$PRGNAM-$VERSION
+mkdir -p $PKGDOC
+chmod 644 doc/menu/*
+cp -a ChangeLog doc/{Change*,FAQ,README*,menu} $PKGDOC
+cat $CWD/$PRGNAM.SlackBuild > $PKGDOC/$PRGNAM.SlackBuild
 
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
