network/clipgrab: New maintainer
Signed-off-by: Christoph Willing <chris.willing@slackbuilds.org>

Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/network/clipgrab/clipgrab.SlackBuild b/network/clipgrab/clipgrab.SlackBuild
--- a/network/clipgrab/clipgrab.SlackBuild
+++ b/network/clipgrab/clipgrab.SlackBuild
@@ -2,6 +2,7 @@
 #
 # Slackware build script for clipgrab.
 #
+# Copyright 2026 Vijay Marcel
 # Copyright 2015-2025  Edinaldo P. Silva, Rio de Janeiro, Brazil.
 # All rights reserved.
 #
@@ -10,6 +11,10 @@
 #
 # 1. Redistributions of this script must retain the above copyright
 #    notice, this list of conditions and the following disclaimer.
+#
+# 2. Redistributions in binary form must reproduce the above copyright
+#    notice, this list of conditions and the following disclaimer in
+#    the documentation and/or other materials provided with the distribution.
 #
 #  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
 #  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
@@ -30,7 +35,7 @@ cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=clipgrab
 VERSION=${VERSION:-3.9.14}
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
 
@@ -51,21 +56,16 @@ TMP=${TMP:-/tmp/SBo}
 PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
 
-if [ "$ARCH" = "i586" ]; then
-  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
-  LIBDIRSUFFIX=""
-elif [ "$ARCH" = "i686" ]; then
-  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
-  LIBDIRSUFFIX=""
+if [ "$ARCH" = "i586" -o "$ARCH" = "i686" ]; then
+  SLKCFLAGS="-march=$ARCH -mtune=i686 -pipe -O2 -fPIC"
 elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2 -fPIC"
-  LIBDIRSUFFIX="64"
+  SLKCFLAGS="-march=x86-64 -mtune=generic -pipe -O2 -fPIC"
 else
-  SLKCFLAGS="-O2"
-  LIBDIRSUFFIX=""
+  echo "This SlackBuild will not run on $ARCH" && exit 1
 fi
 
 set -e
+trap 'echo "$0 FAILED at line $LINENO!" | tee $OUTPUT/error-${PRGNAM}.log' ERR
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
@@ -80,7 +80,7 @@ find -L . \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
   -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \+
 
-qmake-qt5 clipgrab.pro
+qmake-qt5 QMAKE_CXXFLAGS+="$SLKCFLAGS" QMAKE_CFLAGS+="$SLKCFLAGS" clipgrab.pro
 make DESTDIR=$PKG
 
 install -Dm644 $CWD/clipgrab.desktop $PKG/usr/share/applications/clipgrab.desktop
@@ -96,4 +96,4 @@ cat $CWD/doinst.sh > $PKG/install/doinst.sh
 cat $CWD/slack-desc > $PKG/install/slack-desc
 
 cd $PKG
-/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
+/sbin/makepkg -l y -c n --remove-rpaths --remove-tmp-rpaths $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
