network/fail2ban: Updated for version 0.8.3

diff --git a/network/fail2ban/fail2ban.SlackBuild b/network/fail2ban/fail2ban.SlackBuild
--- a/network/fail2ban/fail2ban.SlackBuild
+++ b/network/fail2ban/fail2ban.SlackBuild
@@ -1,16 +1,20 @@
 #!/bin/sh
 
+#################################################################################
+
 # Slackware Package Build Script for fail2ban
+#
+# Home Page http://www.fail2ban.org/wiki/index.php/Main_Page
 
 # Copyright (c) 2007, Nishant Limbachia (nishant@mnspace.net)
 # All rights reserved.
-#
+
 # Redistribution and use of this script, with or without modification, is 
 # permitted provided that the following conditions are met:
-#
+
 # 1. Redistributions of script must retain the above copyright notice, 
 #    this list of conditions and the following disclaimer.
-#
+
 # THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 # "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 # LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
@@ -22,59 +26,68 @@
 # LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 # NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 # SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+  
+#################################################################################
 
 PRGNAM=fail2ban
-VERSION=0.8.2
+VERSION=0.8.3
 ARCH=${ARCH:-noarch}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 
-CWD=$(pwd)
 TMP=${TMP:-/tmp/SBo}
 PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
+CWD=$(pwd)
 
-set -e # Exit on most errors
+# exit on most errors
+set -e
 
+### clean up from previous builds
 rm -fr $PKG $TMP/$PRGNAM-$VERSION
 mkdir -p $PKG $TMP $OUTPUT
+
+### Extracting the source tarballs
 cd $TMP
-tar xvf $CWD/$PRGNAM-$VERSION.tar.bz2
+tar xjvf $CWD/$PRGNAM-$VERSION.tar.bz2
 cd $TMP/$PRGNAM-$VERSION
+
 chown -R root.root .
 find . \
- \( -perm 777 -o -perm 775 -o -perm 771 -o -perm 711 -o -perm 555 -o -perm 551 -o -perm 511 \) \
- -exec chmod 755 {} \; -o \
- \( -perm 666 -o -perm 664 -o -perm 660 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
- -exec chmod 644 {} \;
+\( -perm 777 -o -perm 775 -o -perm 771 -o -perm 711 -o -perm 555 -o -perm 551 -o -perm 511 \) \
+-exec chmod 755 {} \; -o \
+\( -perm 666 -o -perm 664 -o -perm 660 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
+-exec chmod 644 {} \;
 
 python setup.py install --root=$PKG
 
-install -D -m 0644 $CWD/README.SBo $PKG/usr/doc/$PRGNAM-$VERSION/README.SBo
+mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
 cp -a COPYING ChangeLog PKG-INFO README TODO $PKG/usr/doc/$PRGNAM-$VERSION
 
-# Installing man pages
+### installing man pages
 mkdir -p $PKG/usr/man/man1
-install -m 0644 man/*.1 $PKG/usr/man/man1
 
-# Find and compress man pages
-( cd $PKG/usr/man
+install -m 0644 man/fail2ban-client.1 man/fail2ban-regex.1 \
+man/fail2ban-server.1 $PKG/usr/man/man1
+
+# find and compress man pages
+if [ -d $PKG/usr/man ]; then
+  ( cd $PKG/usr/man
   find . -type f -exec gzip -9 {} \;
   for i in $(find . -type l) ; do ln -s $(readlink $i).gz $i.gz ; rm $i ; done
-) 
+  ) 
+fi
 
-# Install startup script
+# install startup script
 install -D -m 0644 $CWD/rc.fail2ban $PKG/etc/rc.d/rc.fail2ban.new
 
-# Install logrotate script
+# install logrotate script
 install -D -m 0644 $CWD/fail2ban.logrotate $PKG/etc/logrotate.d/fail2ban.new
 
-# Make directory for socket and pid file
-mkdir -p $PKG/var/run/fail2ban
-
+### building package
 mkdir -p $PKG/install
-cat $CWD/slack-desc > $PKG/install/slack-desc
 cat $CWD/doinst.sh > $PKG/install/doinst.sh
-
+cat $CWD/slack-desc > $PKG/install/slack-desc
 cd $PKG
 /sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
+
