libraries/pcg-c: Fixes SlackBuild script
Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/libraries/pcg-c/pcg-c.SlackBuild b/libraries/pcg-c/pcg-c.SlackBuild
--- a/libraries/pcg-c/pcg-c.SlackBuild
+++ b/libraries/pcg-c/pcg-c.SlackBuild
@@ -2,7 +2,7 @@
 #
 # Slackware build script for pcg-c
 #
-# Copyright 2019-2026 / Andy Alt / United States
+# Copyright 2026 / Andy Alt / United States
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -26,6 +26,7 @@ cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=pcg-c
 VERSION=${VERSION:-0.94.1}
+SOURCEARCHIVE=$PRGNAM-$VERSION.tar.gz
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
@@ -50,12 +51,14 @@ TMP=${TMP:-/tmp/SBo}
 PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
 
+LIBDIRSUFFIX=""
 if [ "$ARCH" = "i586" ]; then
   SLKCFLAGS="-O2 -march=i586 -mtune=i686"
 elif [ "$ARCH" = "i686" ]; then
   SLKCFLAGS="-O2 -march=i686 -mtune=i686"
 elif [ "$ARCH" = "x86_64" ]; then
   SLKCFLAGS="-O2 -fPIC"
+  LIBDIRSUFFIX="64"
 else
   SLKCFLAGS="-O2"
 fi
@@ -68,12 +71,12 @@ cd $TMP
 rm -rf $PRGNAM-$VERSION
 
 # Read the .info and make sure the md5sum matches.
-if ! echo "$(grep '^MD5SUM=' $CWD/$PRGNAM.info | cut -d'"' -f2)  $CWD/$PRGNAM-$VERSION.tar.gz" | md5sum -c - ; then
-  echo "ERROR: MD5 checksum mismatch for $PRGNAM-$VERSION.tar.xz" >&2
+if ! echo "$(grep '^MD5SUM=' $CWD/$PRGNAM.info | cut -d'"' -f2)  $CWD/$SOURCEARCHIVE" | md5sum -c - ; then
+  echo "ERROR: MD5 checksum mismatch for $SOURCEARCHIVE" >&2
   exit 1
 fi
 
-tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
+tar xvf $CWD/$SOURCEARCHIVE
 cd $PRGNAM-$VERSION
 chown -R root:root .
 find -L . \
@@ -84,15 +87,17 @@ find -L . \
 
 mkdir build
 cd build
-  CFLAGS="$SLKCFLAGS" \
-  CXXFLAGS="$SLKCFLAGS" \
-  meson .. \
-    --buildtype=release \
-    --strip \
-    --prefix=/usr \
-    -Ddocdir=/usr/doc/$PRGNAM-$VERSION
-  ninja
-  DESTDIR=$PKG ninja install
+CFLAGS="$SLKCFLAGS" \
+CXXFLAGS="$SLKCFLAGS" \
+meson .. \
+  --buildtype=release \
+  --strip \
+  --libdir="/usr/lib$LIBDIRSUFFIX" \
+  --prefix=/usr \
+  -Ddocdir=/usr/doc/$PRGNAM-$VERSION
+
+ninja
+meson install --destdir $PKG
 cd ..
 
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
