development/qbs: Updated for version 1.16.0.
Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/development/qbs/qbs.SlackBuild b/development/qbs/qbs.SlackBuild
--- a/development/qbs/qbs.SlackBuild
+++ b/development/qbs/qbs.SlackBuild
@@ -3,7 +3,7 @@
 # Slackware build script for Qbs
 
 # Copyright 2014-2017 Nikos Giotis <nikos.giotis@mail.com>
-# Copyright 2019 Andrzej Telszewski, Szczecin
+# Copyright 2020 Andrzej Telszewski, Szczecin
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -24,7 +24,7 @@
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 PRGNAM=qbs
-VERSION=${VERSION:-1.13.1}
+VERSION=${VERSION:-1.16.0}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 
@@ -55,42 +55,50 @@ else
   LIBDIRSUFFIX=""
 fi
 
-if [ -x /usr/bin/qbs ]; then
+set -e
+
+if which qbs &>/dev/null; then
+  echo "Found \"qbs\" in PATH."
   echo "Please remove any previous Qbs installations before continuing."
+
   exit 1
 fi
-
-set -e
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
+
 rm -rf $PRGNAM-$VERSION
 tar xvf $CWD/$PRGNAM-src-$VERSION.tar.gz
 mv $PRGNAM-src-$VERSION $PRGNAM-$VERSION
 cd $PRGNAM-$VERSION
+
 chown -R root:root .
-find -L . \
- \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
-  -o -perm 511 \) -exec chmod 755 {} \; -o \
- \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
-  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
+chmod -R a-st,u+rwX,go-w+rX .
+
+# Fix for missing *projectgeneratormanager.h*.
 
 patch -p0 < $CWD/corelib-tools.pri.patch
 
 # Adjust docs location.
+
 sed -i "s|share/doc/qbs|doc/qbs-$VERSION|g" doc/doc.pri
 
-qmake-qt5 qbs.pro \
-  QMAKE_CXXFLAGS="$SLKCFLAGS" \
-  QBS_INSTALL_PREFIX=/usr \
-  QBS_LIBRARY_DIRNAME=lib$LIBDIRSUFFIX \
+qmake-qt5 qbs.pro                         \
+  QMAKE_CXXFLAGS="$SLKCFLAGS"             \
+  QBS_INSTALL_PREFIX=/usr                 \
+  QBS_LIBRARY_DIRNAME=lib$LIBDIRSUFFIX    \
   CONFIG+=qbs_enable_project_file_updates
 
 make
 make install INSTALL_ROOT=$PKG
-make docs
-make install_docs INSTALL_ROOT=$PKG
+
+if which qdoc-qt5 &>/dev/null; then
+  make docs
+  make install_docs INSTALL_ROOT=$PKG
+else
+  echo "qdoc-qt5 not found in PATH.  Docs won't be built nor installed."
+fi
 
 find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
   | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
@@ -101,8 +109,8 @@ gzip -9 $PKG/usr/man/man1/qbs.1
 rm -r $PKG/usr/share/man
 
 mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a LGPL_EXCEPTION.txt LICENSE.GPL3-EXCEPT LICENSE.{LGPLv21,LGPLv3} README \
-  $PKG/usr/doc/$PRGNAM-$VERSION
+cp -a CONTRIBUTING.md LGPL_EXCEPTION.txt LICENSE.GPL3-EXCEPT \
+  LICENSE.{LGPLv21,LGPLv3} README.md $PKG/usr/doc/$PRGNAM-$VERSION
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
 mkdir -p $PKG/usr/share/applications
