development/splint: Updated for version 3.1.2

diff --git a/development/splint/splint.SlackBuild b/development/splint/splint.SlackBuild
--- a/development/splint/splint.SlackBuild
+++ b/development/splint/splint.SlackBuild
@@ -5,7 +5,7 @@
 # Modified by the SlackBuilds.org project
 
 PRGNAM=splint
-VERSION=3.1.1
+VERSION=3.1.2
 ARCH=${ARCH:-i486}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
@@ -13,6 +13,9 @@ CWD=$(pwd)
 TMP=${TMP:-/tmp/SBo}
 PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
+
+# Exit immediately if a command exits with a non-zero status.
+set -e
 
 if [ "$ARCH" = "i486" ]; then
   SLKCFLAGS="-O2 -march=i486 -mtune=i686"
@@ -24,8 +27,8 @@ rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP 
 rm -rf $PRGNAM-$VERSION
-tar xzvf $CWD/$PRGNAM-$VERSION.src.tgz || exit 1
-cd $PRGNAM-$VERSION || exit 1
+tar xzvf $CWD/$PRGNAM-$VERSION.src.tgz
+cd $PRGNAM-$VERSION
 chown -R root:root .
 chmod -R u+w,go+r-w,a-s .
 
@@ -37,12 +40,12 @@ CXXFLAGS="$SLKCFLAGS" \
   --sysconfdir=/etc \
   || exit 1
 
-make || exit 1
-make install DESTDIR=$PKG || exit 1
+make
+make install DESTDIR=$PKG
 
 ( cd $PKG
-  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
-  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
+  find . -type f | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
+  find . -type f | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
 )
 
 ( cd $PKG/usr/man
@@ -58,6 +61,7 @@ cd html
 mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION/html
 cp *.htm *.html $PKG/usr/doc/$PRGNAM-$VERSION/html
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
+cat $CWD/README > $PKG/usr/doc/$PRGNAM-$VERSION/README.SBo
 
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
