office/acroread: Updated for version 8.1.2

diff --git a/office/acroread/acroread.SlackBuild b/office/acroread/acroread.SlackBuild
--- a/office/acroread/acroread.SlackBuild
+++ b/office/acroread/acroread.SlackBuild
@@ -2,7 +2,7 @@
 
 # Slackware build script for acroread - binary repackaging
 
-# Copyright 2006-2007  Robby Workman  (http://rlworkman.net)
+# Copyright 2006-2008  Robby Workman  (http://rlworkman.net)
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -25,31 +25,27 @@
 # Thanks to Andrew Brouwers for the original SlackBuild script and for 
 # permission to modify it as needed.
 
-# Modified by the SlackBuilds.org project
-
 PRGNAM=acroread
-VERSION=7.0.9
-ARCH=i386	# Leave this alone for acroread
-BUILD=${BUILD:-3}
+VERSION=8.1.2
+ARCH=i486	# Leave this alone for acroread
+BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
-
-# If you want to keep the PPKLite plugin (you have OpenLDAP installed),
-# then change the value below to NO
-# I've received reports of getting an error message about the plugin
-# even with OpenLDAP installed, so if you get the error, disable the
-# plugin
-REMOVEPPK=YES
 
 CWD=$(pwd)
 TMP=${TMP:-/tmp/SBo}
 PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
 
+#You can use LANG for installing a different lang version of acroread
+ADOBE_LANG=${ADOBE_LANG:-enu}
+
+set -e
+
 rm -rf $PKG 
 mkdir -p $TMP $PKG $OUTPUT
-cd $TMP || exit 1
+cd $TMP
 rm -rf AdobeReader*
-tar -xzvf $CWD/AdobeReader_enu-$VERSION-1.${ARCH}.tar.gz || exit 1
+tar xvf $CWD/AdobeReader_$ADOBE_LANG-$VERSION-1.i486.tar.bz2
 
 # Create directory structure and extract files from archives
 mkdir -p $PKG/opt/acroread $PKG/usr/bin
@@ -57,67 +53,61 @@ cd $PKG/opt/acroread
 tar -xf $TMP/AdobeReader/COMMON.TAR
 tar -xf $TMP/AdobeReader/ILINXR.TAR
 
-# Patch to fix an Adobe bug - see this link for more information:
-# http://www.adobeforums.com/cgi-bin/webx/.3bc35df4
-# Only apply this patch if you experience problems with syntax
-# errors when runnng acroread
-#cat $CWD/acroread-libgtk-sed.patch | patch -p1 || exit 1
+#Some location cleanup
+mv $PKG/opt/acroread/Adobe/* $PKG/opt/acroread/
+rm -rf $PKG/opt/acroread/Adobe
 
 # Remove stuff we don't need
-rm -rf Reader/HowTo
-rm -r Browser/{HowTo,install_browser_plugin}
-
-# Remove access to the PPKLite plugin (eliminate error message)
-if [ "$REMOVEPPK" = "YES" ]; then
-  chmod 000 Reader/intellinux/plug_ins/PPKLite.api
-fi
+rm -rf Reader8/Reader/HowTo
+rm -r Reader8/Browser/{HowTo,install_browser_plugin}
 
 # Add symlink for binary to /usr/bin
 cd $PKG/usr/bin
-  ln -s ../../opt/acroread/bin/acroread acroread
+  ln -s /opt/acroread/Reader8/bin/acroread acroread
 cd -
 
 # Add symlink for browser plugins
 mkdir -p $PKG/usr/lib/mozilla/plugins
 cd $PKG/usr/lib/mozilla/plugins
-  ln -s ../../../../opt/acroread/Browser/intellinux/nppdf.so nppdf.so
+  ln -s /opt/acroread/Reader8/Browser/intellinux/nppdf.so nppdf.so
 cd -
 
 # Add symlink to AdobeReader.xml for correct mimetype
 mkdir -p $PKG/usr/share/mime/packages
 cd $PKG/usr/share/mime/packages
-  ln -s ../../../../opt/acroread/Resource/Support/AdobeReader.xml \
-    AdobeReader.xml
+  rm -f AdobeReader.xml
+  ln -s /opt/acroread/Reader8/Resource/Support/AdobeReader.xml AdobeReader.xml
 cd -
 
 # Fix symlink to .desktop file 
 mkdir -p $PKG/usr/share/{applications,pixmaps}
 cd $PKG/usr/share/applications
-  rm -rf AdobeReader.desktop
-  ln -sf ../../../opt/acroread/Resource/Support/AdobeReader_GNOME.desktop \
+  rm -f AdobeReader.desktop
+  ln -sf /opt/acroread/Reader8/Resource/Support/AdobeReader.desktop \
     AdobeReader.desktop
 cd -
 
 # Link icon to /usr/share/pixmaps
 cd $PKG/usr/share/pixmaps
-  rm -rf AdobeReader.png
-  ln -sf ../../../opt/acroread/Resource/Icons/AdobeReader.png AdobeReader.png
+  rm -f AdobeReader.png
+  ln -sf /opt/acroread/Reader8/Resource/Icons/48x48/AdobeReader8.png AdobeReader8.png
 cd -
 
-# Fix path to icon in .desktop file so that it works with kde in /opt/kde
-sed -i 's%Icon=AdobeReader.png%Icon=/usr/share/pixmaps/AdobeReader.png%' \
-  $PKG/opt/acroread/Resource/Support/AdobeReader_GNOME.desktop || exit 1
+# Move docs to their correct locations
+mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
+cp -a $TMP/AdobeReader/ReadMe.htm $PKG/usr/doc/$PRGNAM-$VERSION
+cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
 cat $CWD/doinst.sh > $PKG/install/doinst.sh
 
-# Fix permissions
+# Fix ownership and permissions
 cd $PKG
 find . -type d -exec chmod 755 {} \;
+chown -R root:root .
 chmod -R a-s,u+w,go+r-w .
 
 # No stripping of binaries and such, as Firefox doesn't like naked acroread :D
 # Just build the package...  ;P
 /sbin/makepkg -p -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
-
