system/virtualxt: Install shared lib in correct place.
Signed-off-by: B. Watson <urchlay@slackware.uk>

Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/system/virtualxt/virtualxt.SlackBuild b/system/virtualxt/virtualxt.SlackBuild
--- a/system/virtualxt/virtualxt.SlackBuild
+++ b/system/virtualxt/virtualxt.SlackBuild
@@ -23,11 +23,17 @@
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 # SOFTWARE.
 
+# 20241018 bkw: Modified by SlackBuilds.org, BUILD=2:
+# - shared lib was being installed to wrong place, so the app failed to run.
+# - use getent to detect the users group (NEVER just grep /etc/group!)
+# Note: the ".vxt modules" are shared libraries, and as such, shouldn't
+# be installed under /usr/share. I'm not going to change this.
+
 cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=virtualxt
 VERSION=${VERSION:-0.11}
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
 
@@ -39,9 +45,6 @@ if [ -z "$ARCH" ]; then
   esac
 fi
 
-# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
-# the name of the created package would be, and then exit. This information
-# could be useful to other scripts.
 if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
   echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
   exit 0
@@ -76,11 +79,8 @@ rm -rf virtualxt-$VERSION
 unzip $CWD/virtualxt-$VERSION.zip
 cd virtualxt-$VERSION
 chown -R root:root .
-find -L . \
- \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 -o -perm 511 \) \
- -exec chmod 755 {} \; -o \
- \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
- -exec chmod 644 {} \;
+find -L .  -perm /111 -a \! -perm 755 -a -exec chmod 755 {} + -o \
+        \! -perm /111 -a \! -perm 644 -a -exec chmod 644 {} +
 
 # Build virtualxt with SDL2 frontend
 which premake5
@@ -99,7 +99,7 @@ make sdl2-frontend modules
 
 install -D -m 0755 build/bin/virtualxt $PKG/usr/bin/virtualxt
 mkdir -p $PKG/usr/lib$LIBDIRSUFFIX/virtualxt
-install -D -m 0755 build/bin/libvxt.so $PKG/usr/lib$LIBDIRSUFFIX/virtualxt/libvxt.so
+install -D -m 0755 build/bin/libvxt.so $PKG/usr/lib$LIBDIRSUFFIX/libvxt.so
 
 # Install BIOS, disk images, and modules
 DSTDIR=$PKG/usr/share/$PRGNAM
@@ -109,7 +109,9 @@ mkdir $DSTDIR/boot && cp boot/*.img $DSTDIR/boot/
 mkdir $DSTDIR/modules && cp modules/*.vxt $DSTDIR/modules/
 
 # Allow all users read access
-if [ "$(grep ^users /etc/group)" = "" ]; then
+# 20241018 bkw: this is redundant; 'users' is a default group on Slackware
+# and will always exist.
+if ! getent group users; then
   echo "ERROR: The users group is missing!"
   exit 1
 fi
