misc/simh-classic: Updated for version 3.12_2.
Signed-off-by: Dave Woodfall <dave@slackbuilds.org>

Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/misc/simh-classic/simh-classic.SlackBuild b/misc/simh-classic/simh-classic.SlackBuild
--- a/misc/simh-classic/simh-classic.SlackBuild
+++ b/misc/simh-classic/simh-classic.SlackBuild
@@ -25,11 +25,11 @@
 cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=simh-classic
-VERSION=${VERSION:-3.11_0}
+VERSION=${VERSION:-3.12_2}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
-BASENAME=${BASENAME:-simhv311-0}
+BASENAME=${BASENAME:-simhv312-2}
 
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
@@ -43,10 +43,6 @@ if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
   echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
   exit 0
 fi
-
-TMP=${TMP:-/tmp/SBo}
-PKG=$TMP/package-$PRGNAM
-OUTPUT=${OUTPUT:-/tmp}
 
 if [ "$ARCH" = "i586" ]; then
   SLKCFLAGS="-O2 -march=i586 -mtune=i686"
@@ -63,27 +59,18 @@ else
 fi
 
 set -e
-
-set -e
-CWD=$(pwd)
 TMP=${TMP:-/tmp/SBo}
 PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
+BUILDDIR=$TMP/$BASENAME
 
-rm -rf $PKG
-mkdir -p $TMP $PKG $OUTPUT
-cd $PKG
+rm -rf $PKG $BUILDDIR
+mkdir -p $TMP $PKG $OUTPUT $BUILDDIR
+cd $BUILDDIR
 
-if [ -e $CWD/$BASENAME.zip ]; then
-  unzip $CWD/$BASENAME.zip
-  mv sim/* .
-  rmdir sim
-  echo
-else
-  echo "Could not find file "$CWD/$BASENAME.zip
-  echo "Aborting..."
-  exit 1
-fi
+unzip $CWD/$BASENAME.zip
+mv sim/* .
+rmdir sim
 
 # Patch the sources in order for uc15 to compile...
 # gzipped to preserve CRLF line endings
@@ -96,35 +83,74 @@ find -L . \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
   -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
 
-chmod 0755 .
-
 # make the simulators
+# Randomly fails with more than one job
 make -j1 all
 
-mkdir -p $PKG/slackbuild/opt/$PRGNAM/bin
-mv BIN/* $PKG/slackbuild/opt/$PRGNAM/bin
+# install & strip binaries
+# The subdirectory BIN/buildtools will cause an exit code > 0 hence || true
+install -Dsv -m 0755 BIN/* -t $PKG/opt/$PRGNAM/bin || true
 
-# Don't ship .la files:
-rm -f $PKG/{,usr/}lib${LIBDIRSUFFIX}/*.la
+# create program symlinks
+mkdir -p $PKG/usr/bin
+( cd $PKG/usr/bin ; rm -rf simh-classic-altair )
+( cd $PKG/usr/bin ; ln -sf ../../opt/simh-classic/bin/altair simh-classic-altair )
+( cd $PKG/usr/bin ; rm -rf simh-classic-eclipse )
+( cd $PKG/usr/bin ; ln -sf ../../opt/simh-classic/bin/eclipse simh-classic-eclipse )
+( cd $PKG/usr/bin ; rm -rf simh-classic-gri )
+( cd $PKG/usr/bin ; rm -rf ../..simh-classic-h316 )
+( cd $PKG/usr/bin ; ln -sf ../../opt/simh-classic/bin/h316 simh-classic-h316 )
+( cd $PKG/usr/bin ; rm -rf simh-classic-i1401 )
+( cd $PKG/usr/bin ; ln -sf ../../opt/simh-classic/bin/i1401 simh-classic-i1401 )
+( cd $PKG/usr/bin ; rm -rf simh-classic-i1620 )
+( cd $PKG/usr/bin ; ln -sf ../../opt/simh-classic/bin/i1620 simh-classic-i1620 )
+( cd $PKG/usr/bin ; rm -rf simh-classic-i7094 )
+( cd $PKG/usr/bin ; ln -sf ../../opt/simh-classic/bin/i7094 simh-classic-i7094 )
+( cd $PKG/usr/bin ; rm -rf simh-classic-id16 )
+( cd $PKG/usr/bin ; ln -sf ../../opt/simh-classic/bin/id16 simh-classic-id16 )
+( cd $PKG/usr/bin ; rm -rf simh-classic-id32 )
+( cd $PKG/usr/bin ; ln -sf ../../opt/simh-classic/bin/id32 simh-classic-id32 )
+( cd $PKG/usr/bin ; rm -rf simh-classic-lgp )
+( cd $PKG/usr/bin ; ln -sf ../../opt/simh-classic/bin/lgp simh-classic-lgp )
+( cd $PKG/usr/bin ; rm -rf simh-classic-nova )
+( cd $PKG/usr/bin ; ln -sf ../../opt/simh-classic/bin/nova simh-classic-nova )
+( cd $PKG/usr/bin ; rm -rf simh-classic-pdp1 )
+( cd $PKG/usr/bin ; ln -sf ../../opt/simh-classic/bin/pdp1 simh-classic-pdp1 )
+( cd $PKG/usr/bin ; rm -rf simh-classic-pdp10 )
+( cd $PKG/usr/bin ; ln -sf ../../opt/simh-classic/bin/pdp10 simh-classic-pdp10 )
+( cd $PKG/usr/bin ; rm -rf simh-classic-pdp11 )
+( cd $PKG/usr/bin ; ln -sf ../../opt/simh-classic/bin/pdp11 simh-classic-pdp11 )
+( cd $PKG/usr/bin ; rm -rf simh-classic-pdp15 )
+( cd $PKG/usr/bin ; ln -sf ../../opt/simh-classic/bin/pdp15 simh-classic-pdp15 )
+( cd $PKG/usr/bin ; rm -rf simh-classic-pdp4 )
+( cd $PKG/usr/bin ; ln -sf ../../opt/simh-classic/bin/pdp4 simh-classic-pdp4 )
+( cd $PKG/usr/bin ; rm -rf simh-classic-pdp7 )
+( cd $PKG/usr/bin ; ln -sf ../../opt/simh-classic/bin/pdp7 simh-classic-pdp7 )
+( cd $PKG/usr/bin ; rm -rf simh-classic-pdp8 )
+( cd $PKG/usr/bin ; ln -sf ../../opt/simh-classic/bin/pdp8 simh-classic-pdp8 )
+( cd $PKG/usr/bin ; rm -rf simh-classic-pdp9 )
+( cd $PKG/usr/bin ; ln -sf ../../opt/simh-classic/bin/pdp9 simh-classic-pdp9 )
+( cd $PKG/usr/bin ; rm -rf simh-classic-sds )
+( cd $PKG/usr/bin ; ln -sf ../../opt/simh-classic/bin/sds simh-classic-sds )
+( cd $PKG/usr/bin ; rm -rf simh-classic-sigma )
+( cd $PKG/usr/bin ; ln -sf ../../opt/simh-classic/bin/sigma simh-classic-sigma )
+( cd $PKG/usr/bin ; rm -rf simh-classic-uc15 )
+( cd $PKG/usr/bin ; ln -sf ../../opt/simh-classic/bin/uc15 simh-classic-uc15 )
+( cd $PKG/usr/bin ; rm -rf simh-classic-vax )
+( cd $PKG/usr/bin ; ln -sf ../../opt/simh-classic/bin/vax simh-classic-vax )
+( cd $PKG/usr/bin ; rm -rf simh-classic-vax780 )
+( cd $PKG/usr/bin ; ln -sf ../../opt/simh-classic/bin/vax780 simh-classic-vax780 )
 
-find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
-  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
+mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
+mv $BUILDDIR/doc/* $PKG/usr/doc/$PRGNAM-$VERSION
+cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
+cat $CWD/pdp11_defs.h.patch.gz > $PKG/usr/doc/$PRGNAM-$VERSION/pdp11_defs.h.patch.gz
 
-mkdir -p $PKG/slackbuild/usr/doc/$PRGNAM-$VERSION
-cp -a \
-  doc/* \
-  $PKG/slackbuild/usr/doc/$PRGNAM-$VERSION
-cat $CWD/$PRGNAM.SlackBuild > $PKG/slackbuild/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
-cat $CWD/pdp11_defs.h.patch.gz > $PKG/slackbuild/usr/doc/$PRGNAM-$VERSION/pdp11_defs.h.patch.gz
+( cd $PKG/opt/$PRGNAM ; rm -rf doc )
+( cd $PKG/opt/$PRGNAM ; ln -sf ../../usr/doc/$PRGNAM-$VERSION doc )
 
-mkdir -p $PKG/slackbuild/opt/$PRGNAM/doc/$PRGNAM-$VERSION
-cp -a doc/*  $PKG/slackbuild/opt/$PRGNAM/doc/
-cat $CWD/$PRGNAM.SlackBuild > $PKG/slackbuild/opt/$PRGNAM/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
+mkdir -p $PKG/install
+cat $CWD/slack-desc > $PKG/install/slack-desc
 
-
-mkdir -p $PKG/slackbuild/install
-cat $CWD/slack-desc > $PKG/slackbuild/install/slack-desc
-cat $CWD/doinst.sh > $PKG/slackbuild/install/doinst.sh
-
-cd $PKG/slackbuild/
+cd $PKG/
 /sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
