system/clamsmtp: Updated for version 1.10

diff --git a/system/clamsmtp/clamsmtp.SlackBuild b/system/clamsmtp/clamsmtp.SlackBuild
--- a/system/clamsmtp/clamsmtp.SlackBuild
+++ b/system/clamsmtp/clamsmtp.SlackBuild
@@ -1,16 +1,20 @@
 #!/bin/sh
 
+#################################################################################
+
 # Slackware Package Build Script for clamsmtp
+
+# Home Page http://memberwebs.com/stef/software/clamsmtp/
 
 # Copyright (c) 2007, Nishant Limbachia (nishant@mnspace.net)
 # All rights reserved.
 
 # Redistribution and use of this script, with or without modification, is 
 # permitted provided that the following conditions are met:
-#
+
 # 1. Redistributions of script must retain the above copyright notice, 
 #    this list of conditions and the following disclaimer.
-#
+
 # THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 # "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 # LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
@@ -23,76 +27,87 @@
 # NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 # SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-# Modified by Robby Workman <rworkman@slackbuilds.org> for better consistency
-# with other scripts in our repository - no new license terms.
+#################################################################################
 
 PRGNAM=clamsmtp
-VERSION=1.9
+VERSION=1.10
 ARCH=${ARCH:-i486}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
-CWD=$(pwd)
+
 TMP=${TMP:-/tmp/SBo}
 PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
+CWD=$(pwd)
+
+set -e
 
 if [ "$ARCH" = "i486" ]; then
   SLKCFLAGS="-O2 -march=i486 -mtune=i686"
 elif [ "$ARCH" = "i686" ]; then
   SLKCFLAGS="-O2 -march=i686 -mtune=i686"
+elif [ "$ARCH" = "x86_64" ]; then
+  SLKCFLAGS="-O2 -fPIC"
 fi
 
-rm -rf $PKG $TMP/$PRGNAM-$VERSION
+### clean up from previous builds
+rm -fr $TMP/$PRGNAM-$VERSION $PKG
 mkdir -p $TMP $PKG $OUTPUT
+
+### Extracting the source tarballs
 cd $TMP
-tar xvf $CWD/$PRGNAM-$VERSION.tar.gz || exit 1
-cd $PRGNAM-$VERSION || exit 1
+tar xzvf $CWD/$PRGNAM-$VERSION.tar.gz
+cd $TMP/$PRGNAM-$VERSION
+
 chown -R root.root .
+
 find . \
- \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
- -exec chmod 755 {} \; -o \
- \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
- -exec chmod 644 {} \;
+\( -perm 664 -o -perm 666 -o -perm 600 -o -perm 440 -o -perm 444 -o -perm 400 \) \
+-exec chmod 644 {} \;
 
+find . \
+\( -perm 777 -o -perm 755 -o -perm 711 -o -perm 700 -o -perm 555 -o -perm 511 -o -perm 500 \) \
+-exec chmod 755 {} \;
+
+### configure the package
 CFLAGS="$SLKCFLAGS" \
-./configure \
-  --prefix=/usr \
-  --exec-prefix=/usr \
-  --sysconfdir=/etc \
-  --localstatedir=/var \
-  --datarootdir=/usr \
-  --mandir=/usr/man \
-  --program-prefix="" \
-  --program-suffix="" \
-  --build=$ARCH-slackware-linux \
-  || exit 1
+./configure --prefix=/usr \
+--exec-prefix=/usr \
+--sysconfdir=/etc \
+--localstatedir=/var \
+--mandir=/usr/man \
+--datarootdir=/usr \
+--program-prefix="" \
+--program-suffix="" \
+--build=${ARCH}-slackware-linux
 
-make || exit 1
-make install DESTDIR=$PKG || exit 1
+make
+make install DESTDIR=$PKG
 
+### copying essential doc files
 mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a AUTHORS ChangeLog COPYING INSTALL NEWS README TODO \
-  $PKG/usr/doc/$PRGNAM-$VERSION
 
+cp -a AUTHORS ChangeLog COPYING INSTALL NEWS \
+README $PKG/usr/doc/$PRGNAM-$VERSION
+
+### stripping binaries
 ( cd $PKG
-  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
+  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
   find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
 )
 
-find $PKG/usr/man -name "*.?" -type f 2> /dev/null | xargs gzip -9 2> /dev/null
+( cd $PKG/usr/man
+  find . -type f -exec gzip -9 {} \;
+  for i in $(find . -type l) ; do ln -s $(readlink $i).gz $i.gz ; rm $i ; done
+) 
 
-if [ -d $PKG/usr/info ]; then
-  rm -f $PKG/usr/info/dir
-  find $PKG/usr/info -name "*.info" -type f 2> /dev/null | xargs gzip -9 2> /dev/null
-fi
-
-mkdir -p $PKG/etc/rc.d
+# putting slack-desc and doinst.sh in place
+mkdir -p $PKG/install $PKG/etc/rc.d
+cat $CWD/slack-desc > $PKG/install/slack-desc
+cat $CWD/doinst.sh > $PKG/install/doinst.sh
 cat $CWD/rc.clamsmtpd > $PKG/etc/rc.d/rc.clamsmtpd.new
 cat $TMP/$PRGNAM-$VERSION/doc/clamsmtpd.conf > $PKG/etc/clamsmtpd.conf.new
 
-mkdir -p $PKG/install
-cat $CWD/doinst.sh > $PKG/install/doinst.sh
-cat $CWD/slack-desc > $PKG/install/slack-desc
-
+### building package
 cd $PKG
 /sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
