system/wine: re-added legacy multilib support.
Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/system/wine/wine.SlackBuild b/system/wine/wine.SlackBuild
--- a/system/wine/wine.SlackBuild
+++ b/system/wine/wine.SlackBuild
@@ -28,7 +28,8 @@ cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=wine
 VERSION=${VERSION:-9.0}
-BUILD=${BUILD:-2}
+ARCHS="i386,x86_64"
+BUILD=${BUILD:-3}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
 
@@ -78,6 +79,26 @@ case "$ARCH" in
   ;;
 esac
 
+MULTILIB=${MULTILIB@L}
+if [[ "$ARCH" != "x86_64" && "$MULTILIB" = "yes" ]]; then
+  echo "Cannot build for multilib on non-64bit systems."
+  exit 1
+elif [[ "$ARCH" = "x86_64" && "$MULTILIB" = "yes"  ]]; then
+  WINETMP="$( mktemp -d $TMP/wine-test-XXXXXX )"
+  echo "int main(void) {; return(0); }" > "$WINETMP/test.c"
+  gcc -m32 "$WINETMP/test.c" -o /dev/null >/dev/null 2>&1 && WINE32TEST=${WINE32TEST:-yes}
+  rm -rf "$WINETMP"
+  if [[ $WINE32TEST = "yes" ]]; then
+    ARCHS="x86_64"
+    WINE32="yes"
+  else
+    echo "MULTILIB was requested, however the multilib test has failed."
+    echo "Have the compat32 libraries been installed?"
+    echo "Please see README.MULTILIB"
+    exit 1
+  fi
+fi
+
 set -e
 
 rm -rf $PKG
@@ -115,7 +136,7 @@ if [ "$WINE64" = "yes" ]; then
      --sysconfdir=/etc \
      --mandir=/usr/man \
      --enable-win64 \
-     --enable-archs="i386,x86_64" \
+     --enable-archs=$ARCHS \
      --with-x \
      --with-gnutls \
      --${do_opengl}-opengl \
