system/kc: Don't block build completely with call to read.
A raw read call means we can't easily automatically test this build.
Other builds have similar handling - xview, zseal, xmms-cue, etc,
but they all have a max timeout so the build is not completely
blocked.

Signed-off-by: Andrew Clemons <andrew.clemons@gmail.com>

Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/system/kc/kc.SlackBuild b/system/kc/kc.SlackBuild
--- a/system/kc/kc.SlackBuild
+++ b/system/kc/kc.SlackBuild
@@ -67,7 +67,8 @@ set -e
 
 printf "\n\n"
 echo "Please read /usr/doc/$PRGNAM-$VERSION/Changelog.md after installation to see why you might not be able to open your database anymore."
-echo 'Press enter to continue...';read
+echo 'Press Ctrl-C within ten seconds to abort, or press enter to continue...'
+read -t 10 || true
 printf "\n\n"
 
 rm -rf $PKG
