libraries/canfigger: Updated for version 0.3.2.
Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/libraries/canfigger/canfigger.SlackBuild b/libraries/canfigger/canfigger.SlackBuild
--- a/libraries/canfigger/canfigger.SlackBuild
+++ b/libraries/canfigger/canfigger.SlackBuild
@@ -22,7 +22,8 @@
 cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=canfigger
-VERSION=${VERSION:-0.3.1}
+VERSION=${VERSION:-0.3.2}
+SOURCEARCHIVE=$PRGNAM-$VERSION.tar.xz
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
@@ -67,8 +68,8 @@ cd $TMP
 rm -rf $PRGNAM-$VERSION
 
 # Read the .info and make sure the md5sum matches.
-if ! echo "$(grep '^MD5SUM=' $CWD/canfigger.info | cut -d'"' -f2)  $CWD/$PRGNAM-$VERSION.tar.xz" | md5sum -c - ; then
-  echo "ERROR: MD5 checksum mismatch for $PRGNAM-$VERSION.tar.xz" >&2
+if ! echo "$(grep '^MD5SUM=' $CWD/$PRGNAM.info | cut -d'"' -f2)  $CWD/$SOURCEARCHIVE" | md5sum -c - ; then
+  echo "ERROR: MD5 checksum mismatch for $SOURCEARCHIVE" >&2
   exit 1
 fi
 
@@ -90,17 +91,17 @@ meson .. \
   --strip \
   --libdir="/usr/lib$LIBDIRSUFFIX" \
   --prefix=/usr \
-  -Ddocdir=/usr/doc/$PRGNAM-$VERSION \
-  -Ddefault_library=both
+  -Ddocdir=/usr/doc/$PRGNAM-$VERSION
 
-ninja -v
-DESTDIR=$PKG ninja install
+ninja
+meson install --destdir $PKG
 cd ..
 
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
+cat $CWD/doinst.sh > $PKG/install/doinst.sh
 
 cd $PKG
 /sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
