audio/synthv1: Updated for version 1.1.1.
Signed-off-by: B. Watson <urchlay@slackware.uk>

Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/audio/synthv1/synthv1.SlackBuild b/audio/synthv1/synthv1.SlackBuild
--- a/audio/synthv1/synthv1.SlackBuild
+++ b/audio/synthv1/synthv1.SlackBuild
@@ -6,6 +6,7 @@
 
 # Licensed under the WTFPL. See http://www.wtfpl.net/txt/copying/ for details.
 
+# 20240925 bkw: update for 1.1.1.
 # 20240815 bkw: update for 1.0.0
 # 20230629 bkw: update for v0.9.31
 # 20230109 bkw: update for v0.9.28
@@ -28,7 +29,7 @@
 cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=synthv1
-VERSION=${VERSION:-1.0.0}
+VERSION=${VERSION:-1.1.1}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
@@ -66,6 +67,20 @@ fi
 
 set -e
 
+# 20240925 bkw: If jack is missing, the build doesn't fail right away.
+# Instead, it compiles for a while, then 'make install/strip' fails.
+# Better to abort immediately in that case.
+if ! pkg-config --exists jack; then
+  cat <<EOF
+
+*****************************************************************
+* Missing required dependency jack. Install it, then try again. *
+*****************************************************************
+
+EOF
+  exit 1
+fi
+
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
@@ -73,8 +88,8 @@ rm -rf $PRGNAM-$VERSION
 tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
 cd $PRGNAM-$VERSION
 chown -R root:root .
-find -L .  -perm /111 -a \! -perm 755 -a -exec chmod 755 {} \+ -o \
-        \! -perm /111 -a \! -perm 644 -a -exec chmod 644 {} \+
+find -L .  -perm /111 -a \! -perm 755 -a -exec chmod 755 {} + -o \
+        \! -perm /111 -a \! -perm 644 -a -exec chmod 644 {} +
 
 # 20240815 bkw: lv2 is supposed to be autodetected, but if it's
 # missing, the build fails unless we explicitly disable. So:
@@ -84,6 +99,11 @@ pkg-config --exists lv2 && LV2_OPT="ON"
 # This thing can't be told to use qmake-qt5, and keeps choking on
 # /usr/bin/qmake. The --with-qt option doesn't help, only putting
 # qt5's bin/ before /usr/bin in $PATH will do.
+
+# 20240925 bkw: Add -DCONFIG_QT6=0, to avoid it autodetecting and
+# using qt6 if installed. Not interested in dealing with it, and the
+# qt5 UI works fine.
+
 export PATH=/usr/lib$LIBDIRSUFFIX/qt5/bin:$PATH
 
 mkdir -p build
@@ -91,6 +111,7 @@ cd build
   cmake \
     -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
     -DCONFIG_LV2=$LV2_OPT \
+    -DCONFIG_QT6=0 \
     -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
     -DCMAKE_INSTALL_MANDIR=/usr/man \
     -DCMAKE_INSTALL_PREFIX=/usr \
@@ -149,9 +170,10 @@ for i in man1 fr/man1 fr.UTF-8/man1; do
   ln -s $PRGNAM.1.gz $PKG/usr/man/$i/${PRGNAM}_jack.1.gz
 done
 
-mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a ChangeLog README LICENSE $PKG/usr/doc/$PRGNAM-$VERSION
-cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
+PKGDOC=$PKG/usr/doc/$PRGNAM-$VERSION
+mkdir -p $PKGDOC
+cp -a ChangeLog README LICENSE $PKGDOC
+cat $CWD/$PRGNAM.SlackBuild > $PKGDOC/$PRGNAM.SlackBuild
 
 LIBLO=no
 LV2=no
