graphics/qcad: Updated for version 3.32.9.0 + new maintainer
Signed-off-by: Christoph Willing <chris.willing@slackbuilds.org>

Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/graphics/qcad/qcad.SlackBuild b/graphics/qcad/qcad.SlackBuild
--- a/graphics/qcad/qcad.SlackBuild
+++ b/graphics/qcad/qcad.SlackBuild
@@ -2,6 +2,7 @@
 
 # Slackware build script for qcad
 
+# Copyright 2026 Vijay Marcel
 # Copyright 2013-2019 Larry Hajali <larryhaja[at]gmail[dot]com>
 # All rights reserved.
 #
@@ -10,6 +11,10 @@
 #
 # 1. Redistributions of this script must retain the above copyright
 #    notice, this list of conditions and the following disclaimer.
+#
+# 2. Redistributions in binary form must reproduce the above copyright
+#    notice, this list of conditions and the following disclaimer in
+#    the documentation and/or other materials provided with the distribution.
 #
 #  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
 #  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
@@ -25,7 +30,7 @@
 cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=qcad
-VERSION=${VERSION:-3.26.2.0}
+VERSION=${VERSION:-3.32.9.0}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
@@ -38,9 +43,6 @@ if [ -z "$ARCH" ]; then
   esac
 fi
 
-# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
-# the name of the created package would be, and then exit. This information
-# could be useful to other scripts.
 if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
   echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
   exit 0
@@ -50,21 +52,14 @@ TMP=${TMP:-/tmp/SBo}
 PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
 
-if [ "$ARCH" = "i586" ]; then
-  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
-  LIBDIRSUFFIX=""
-elif [ "$ARCH" = "i686" ]; then
-  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
-  LIBDIRSUFFIX=""
-elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2 -fPIC"
-  LIBDIRSUFFIX="64"
+if [ "$ARCH" = "x86_64" ]; then
+  SLKCFLAGS="-march=x86-64 -mtune=generic -pipe -O2 -fPIC"
 else
-  SLKCFLAGS="-O2"
-  LIBDIRSUFFIX=""
+   echo "This SlackBuild will not run on $ARCH" && exit 1
 fi
 
 set -e
+trap 'echo "$0 FAILED at line $LINENO!" | tee -a $OUTPUT/error-${PRGNAM}.log' ERR
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
@@ -75,76 +70,38 @@ cd $PRGNAM-$VERSION
 chown -R root:root .
 find -L . \
  \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
-  -o -perm 511 \) -exec chmod 755 {} \; -o \
+  -o -perm 511 \) -exec chmod 755 {} \+ -o \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
-  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
+  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \+
 
-# Build with Qt5/Qt4. Default is Qt5.
-if [ "${QT5:-yes}" == "yes" ]; then
-  sed -i 's|$${QT_VERSION}|5.15.2|' src/3rdparty/3rdparty.pro
-  qmake-qt5 QMAKE_CFLAGS+="$SLKCFLAGS" QMAKE_CXXFLAGS+="$SLKCFLAGS" \
-    CONFIG+=release -o Makefile $PRGNAM.pro
-  QTDIRECTORY="qt5"
-else
-  qmake QMAKE_CFLAGS+="$SLKCFLAGS" QMAKE_CXXFLAGS+="$SLKCFLAGS" \
-    CONFIG+=release -o Makefile $PRGNAM.pro
-  QTDIRECTORY="qt"
-fi
+mkdir -pv $PKG/usr/share/$PRGNAM
+mkdir -pv $PKG/usr/man/man1
+mkdir -pv $PKG/usr/bin
 
+qmake-qt5 QMAKE_CFLAGS+="$SLKCFLAGS" QMAKE_CXXFLAGS+="$SLKCFLAGS" CONFIG+=release -o Makefile $PRGNAM.pro
 make
 
-# Need to manually install files.
-mkdir -p $PKG/usr/share/$PRGNAM $PKG/usr/bin $PKG/usr/man/man1
-cp -ar examples fonts libraries linetypes patterns plugins scripts ts $PKG/usr/share/$PRGNAM
-cp release/* $PKG/usr/share/$PRGNAM
-install -m 0755 $CWD/$PRGNAM.sh $PKG/usr/bin/$PRGNAM
-install -m 0644 $PRGNAM.1 $PKG/usr/man/man1
+mkdir -pv $PKG/opt/qcad
+cp -ar examples fonts libraries linetypes patterns scripts ts themes $PKG/usr/share/$PRGNAM
+cp -av release/* $PKG/opt/qcad
+cp -av plugins $PKG/opt/qcad
 
-# Don't repackage libraries that already come with Qt4/Qt5.
-rm -f $PKG/usr/share/$PRGNAM/plugins/designer/{libqwebview.so,readme.txt} \
-  $PKG/usr/share/$PRGNAM/plugins/sqldrivers/* \
-  $PKG/usr/share/$PRGNAM/plugins/imageformats/*
-
-ln -s /usr/lib${LIBDIRSUFFIX}/${QTDIRECTORY}/plugins/designer/libqwebview.so \
-  $PKG/usr/share/$PRGNAM/plugins/designer/libqwebview.so
-for i in /usr/lib${LIBDIRSUFFIX}/${QTDIRECTORY}/plugins/imageformats/*.so; do
-  ln -s $i $PKG/usr/share/$PRGNAM/plugins/imageformats/$(basename $i)
-done
-for i in /usr/lib${LIBDIRSUFFIX}/${QTDIRECTORY}/plugins/sqldrivers/*.so; do
-  ln -s $i $PKG/usr/share/$PRGNAM/plugins/sqldrivers/$(basename $i)
-done
-
-if [ "$QT5" == "yes" ]; then
-  rm -rf $PKG/usr/share/$PRGNAM/plugins/codecs \
-    $PKG/usr/share/$PRGNAM/plugins/printsupport/*
-  for i in /usr/lib${LIBDIRSUFFIX}/${QTDIRECTORY}/plugins/printsupport/*; do
-    ln -s $i $PKG/usr/share/$PRGNAM/plugins/printsupport/$(basename $i)
-  done
-else
-  rm -rf $PKG/usr/share/$PRGNAM/plugins/codecs/* \
-    $PKG/usr/share/$PRGNAM/plugins/printsupport
-  for i in /usr/lib${LIBDIRSUFFIX}/${QTDIRECTORY}/plugins/codecs/*; do
-    ln -s $i $PKG/usr/share/$PRGNAM/plugins/codecs/$(basename $i)
-  done
-fi
-
-find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
-  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
-
-mkdir -p $PKG/usr/share/applications
-install -m 0644 $CWD/$PRGNAM.desktop $PKG/usr/share/applications
-
-find $PKG/usr/man -type f -exec gzip -9 {} \;
+mkdir -pv $PKG/usr/share/applications
+install -vm 0644 $CWD/$PRGNAM.desktop $PKG/usr/share/applications
 
 for i in 16 32 48 64 96 128; do
   convert scripts/${PRGNAM}_icon.png -resize ${i}x${i}! $PRGNAM-$i.png
-  install -D -m 0644 $PRGNAM-$i.png $PKG/usr/share/icons/hicolor/${i}x${i}/apps/$PRGNAM.png
-done
+  install -Dvm 0644 $PRGNAM-$i.png $PKG/usr/share/icons/hicolor/${i}x${i}/apps/$PRGNAM.png
+done 
 
-# A little clean up.
-find $PKG \( -name "*\.pro" -o -name "*\.pri" -o -name "*\.a" \
-  -o -name "*\.ts" -o -name "\.gitignore" \) -exec rm -f '{}' \;
-find $PKG -type d -empty -delete
+install -vm 0755 $CWD/$PRGNAM.sh $PKG/usr/bin/$PRGNAM
+install -vm 0644 $PRGNAM.1 $PKG/usr/man/man1
+
+find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" |
+  grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded --remove-section=.comment --remove-section=.note 2> /dev/null || true
+
+find $PKG/usr/man -type f -exec gzip -9 {} \;
+for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
 
 mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
 cp -a *.txt README.md $PKG/usr/doc/$PRGNAM-$VERSION
@@ -155,4 +112,4 @@ cat $CWD/slack-desc > $PKG/install/slack-desc
 cat $CWD/doinst.sh > $PKG/install/doinst.sh
 
 cd $PKG
-/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
+/sbin/makepkg -l y -c n --remove-rpaths --remove-tmp-rpaths $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
